/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg;
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__pGKepcbONSu6mlrtFDHLIQ[130001];
typedef NU8 tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ;
struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg {
NU32 gs;
NU32 fs;
NU32 es;
NU32 ds;
NU32 edi;
NU32 esi;
NU32 ebp;
NU32 esp;
NU32 ebx;
NU32 edx;
NU32 ecx;
NU32 eax;
NU32 int_no;
NU32 err_code;
NU32 eip;
NU32 cs;
NU32 eflags;
NU32 useresp;
NU32 ss;
};
typedef NimStringV2 tyArray__c2QNJmc34bMEk131Zq7ttQ[32];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs, void* ClE_0);
void* ClE_0;
} tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ;
typedef tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ tyArray__go59cYo0lifoWWnigBty2Tg[16];
N_NIMCALL(void, install)(void);
N_LIB_PRIVATE N_NIMCALL(void, consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ)(NimStringV2 a);
N_NIMCALL(void, gdtInstall)(void);
N_NIMCALL(void, idtInstall)(void);
N_NIMCALL(void, isrsInstall)(void);
N_NIMCALL(void, irqInstall)(void);
N_NIMCALL(void, keyboardInstall)(void);
N_NIMCALL(void, kmain)(void* header, NI b2);
N_LIB_PRIVATE N_NIMCALL(void, screenClear__D9aD4l7GWk79biaBOEO4jNpA)(tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ color);
N_NIMCALL(void, fault_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs);
N_LIB_PRIVATE N_NIMCALL(void, consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2)(NimStringV2 a);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GF7fBXzeJgtHVCogYAjhKw)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___s7Xz6U8AnHt9bxaO3CZFs2w)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, unknown_isrsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, unknown_irqInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern NIM_CHAR* vram__neZY9aEi0xFObl6yu5s62tQ;
extern NI consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw;
extern NI consoleY__rhX8TITk3JYo0RfIllnv1Q;
extern tyArray__c2QNJmc34bMEk131Zq7ttQ exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw;
extern tyArray__go59cYo0lifoWWnigBty2Tg irq_routines__YajyNUbwz3nSWLLa5toz3g;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[7+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_2 = { 7, NIM_NIL, "install" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_3 = {7, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_2};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[7+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_4 = { 7, NIM_NIL, "welcome" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_5 = {7, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_4};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[80+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_6 = { 80, NIM_NIL, "==============================================================="
"=================" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_7 = {80, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_6};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[14+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_8 = { 14, NIM_NIL, "Got exception " };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_9 = {14, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_8};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[2+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_10 = { 2, NIM_NIL, ": " };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_11 = {2, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_10};
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_12 = {80, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_6};
N_NIMCALL(void, install)(void) {	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_3);
	gdtInstall();
	idtInstall();
	isrsInstall();
	irqInstall();
	keyboardInstall();
}
N_NIMCALL(void, kmain)(void* header, NI b2) {	vram__neZY9aEi0xFObl6yu5s62tQ = ((NIM_CHAR*) 753664);
	consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw = ((NI) 1);
	consoleY__rhX8TITk3JYo0RfIllnv1Q = ((NI) 0);
	screenClear__D9aD4l7GWk79biaBOEO4jNpA(((tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ) 15));
	install();
	  __asm__ __volatile__ ("sti");
  
	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_5);
}
N_NIMCALL(void, fault_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs) {	{
		if (!((NU32)((*regs).int_no) < (NU32)(((NU32) 32)))) goto LA3_;
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_7);
		consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2(TM__R8RUzYq41iOx0I9bZH5Nyrw_9);
		consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2(TM__R8RUzYq41iOx0I9bZH5Nyrw_11);
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[((*regs).int_no)- 0]);
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_12);
	}
	LA3_: ;
}

void PreMainInner(void) {
	stdlib_allocatorsInit000();
	unknown_isrsInit000();
	unknown_irqInit000();
}

int cmdCount;
char** cmdLine;
char** gEnv;
void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	stdlib_allocatorsDatInit000();
	systemInit000();
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	eqdestroy___GF7fBXzeJgtHVCogYAjhKw(exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw);
	eqdestroy___s7Xz6U8AnHt9bxaO3CZFs2w(irq_routines__YajyNUbwz3nSWLLa5toz3g);
}
}

