/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "setjmp.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ;
typedef struct tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g;
typedef struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ tySequence__P3ZXR4R07tiqmqKWxuHhKQ;
typedef struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content;
typedef struct tySequence__L2PnSpJoHRFiFGA8kZnz3A tySequence__L2PnSpJoHRFiFGA8kZnz3A;
typedef struct tySequence__L2PnSpJoHRFiFGA8kZnz3A_Content tySequence__L2PnSpJoHRFiFGA8kZnz3A_Content;
typedef struct tyObject_ProcesscolonObjectType___Vh0UOZ7eoJ3cl9azhciMypA tyObject_ProcesscolonObjectType___Vh0UOZ7eoJ3cl9azhciMypA;
typedef struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
struct RootObj {
TNimType* m_type;
};
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
NU raiseId;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc__NT9bSe2DDkjdtx7j9aov2Z6g;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc__NT9bSe2DDkjdtx7j9aov2Z6g raiseAction;
};
typedef NIM_CHAR tyArray__pGKepcbONSu6mlrtFDHLIQ[130001];
typedef NU8 tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ;
struct tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ {
tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA* filesystem;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA {
tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* root;
tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* current;
};
struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ {
  NI len; tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content* p;
};
typedef NU8 tyEnum_FileKind__rqsxzaEqmlcOYhjylXOBbQ;
struct tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g {
NimStringV2 name;
tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* parent;
tyEnum_FileKind__rqsxzaEqmlcOYhjylXOBbQ kind;
union{
struct {tySequence__P3ZXR4R07tiqmqKWxuHhKQ children;
};
struct {NimStringV2 text;
};
};
};
struct tySequence__L2PnSpJoHRFiFGA8kZnz3A {
  NI len; tySequence__L2PnSpJoHRFiFGA8kZnz3A_Content* p;
};
struct tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ {
tySequence__L2PnSpJoHRFiFGA8kZnz3A processes;
tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* context;
};
struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg {
NU32 gs;
NU32 fs;
NU32 es;
NU32 ds;
NU32 edi;
NU32 esi;
NU32 ebp;
NU32 esp;
NU32 ebx;
NU32 edx;
NU32 ecx;
NU32 eax;
NU32 int_no;
NU32 err_code;
NU32 eip;
NU32 cs;
NU32 eflags;
NU32 useresp;
NU32 ss;
};
typedef NimStringV2 tyArray__c2QNJmc34bMEk131Zq7ttQ[32];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs, void* ClE_0);
void* ClE_0;
} tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ;
typedef tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ tyArray__go59cYo0lifoWWnigBty2Tg[16];
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap;AllocatorObj* allocator;tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
#define tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content { NI cap;AllocatorObj* allocator;tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
#define tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content { NI cap;AllocatorObj* allocator;tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
#define tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content { NI cap;AllocatorObj* allocator;tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__L2PnSpJoHRFiFGA8kZnz3A_Content_PP
#define tySequence__L2PnSpJoHRFiFGA8kZnz3A_Content_PP
struct tySequence__L2PnSpJoHRFiFGA8kZnz3A_Content { NI cap;AllocatorObj* allocator;tyObject_ProcesscolonObjectType___Vh0UOZ7eoJ3cl9azhciMypA* data[SEQ_DECL_SIZE];};
#endif

      N_NIMCALL(void, kmain)(void* header, NI b2);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(void, screenClear__D9aD4l7GWk79biaBOEO4jNpA)(tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ color);
N_LIB_PRIVATE N_NIMCALL(void, consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ)(NimStringV2 a);
N_NIMCALL(void, keyboardInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___4ViRAnT6CZeQCXJ9a9bZ5d4A)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ** dest, tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___kNpszSK9bonJaxhSTc9c9cCKw)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* dest);
static N_INLINE(void, nimDecWeakRef)(void* p);
N_NIMCALL(void, nimRawDispose)(void* p);
N_NIMCALL(void*, nimNewObj)(NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*, file__YynSnpl3scimYAz0bfxHHw)(NimStringV2 name, tySequence__P3ZXR4R07tiqmqKWxuHhKQ children);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___IRi9akuRLCCwYQUuXGa9cYmA)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest, tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___5mNWyPlATqYO1X49aafjlqw)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___61f9c4QwTuBqt6IZB6V6HPQ)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, eq___IRi9akuRLCCwYQUuXGa9cYmA_2)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest, tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* src);
static N_INLINE(void, nimIncRef)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eq___420KhbivyBN35wS61Ta50A)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* dest, tySequence__P3ZXR4R07tiqmqKWxuHhKQ src);
N_LIB_PRIVATE N_NIMCALL(void, setLen__9cFY9csU2Vy6aqPrO9bDoi0NA)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* s, NI newlen);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA_2)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize);
N_LIB_PRIVATE N_NIMCALL(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*, file__79c2zL1OCIGk68k8sohkCpw)(NimStringV2 name, NimStringV2 text);
N_LIB_PRIVATE N_NIMCALL(void, ls__Mv3qRLY5H101D3bjLdhq7w)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* context);
N_LIB_PRIVATE N_NIMCALL(void, consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2)(NimStringV2 a);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___hkiPLzq0zzi3PkuQM12MSQ)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ** dest, tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___T9cM9cEzGIc4S3YkIu5hJtDA)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___0p85KOjIVfNWTXEpPsMmNg)(tySequence__L2PnSpJoHRFiFGA8kZnz3A* dest);
N_LIB_PRIVATE N_NIMCALL(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ*, initScheduler__ykdhg9awcGH79b40fvlTKNrg)(void);
N_LIB_PRIVATE N_NIMCALL(void, schedule__RbdIHPlbvO5wzDKmqY9cxtQ)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* scheduler, tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* context);
N_LIB_PRIVATE N_NIMCALL(void, eq___4ViRAnT6CZeQCXJ9a9bZ5d4A_2)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ** dest, tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GGAcUKitkAdlBRC7Qo4Bow)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___Iwx4PQuj2wDcj4AOFrZi0Q)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ** dest);
N_NIMCALL(void, install)(void);
N_NIMCALL(void, gdtInstall)(void);
N_NIMCALL(void, idtInstall)(void);
N_NIMCALL(void, isrsInstall)(void);
N_NIMCALL(void, irqInstall)(void);
N_NIMCALL(void, fault_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GF7fBXzeJgtHVCogYAjhKw)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___s7Xz6U8AnHt9bxaO3CZFs2w)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, unknown_isrsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, unknown_irqInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern NIM_CHAR* vram__neZY9aEi0xFObl6yu5s62tQ;
extern NI consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw;
extern NI consoleY__rhX8TITk3JYo0RfIllnv1Q;
extern tyArray__c2QNJmc34bMEk131Zq7ttQ exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw;
extern tyArray__go59cYo0lifoWWnigBty2Tg irq_routines__YajyNUbwz3nSWLLa5toz3g;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[7+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_3 = { 7, NIM_NIL, "welcome" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_4 = {7, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_3};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[1+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_6 = { 1, NIM_NIL, "/" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_7 = {1, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_6};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[1+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_8 = { 1, NIM_NIL, "a" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_9 = {1, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_8};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[0+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_10 = { 0, NIM_NIL, "" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_11 = {0, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_10};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[1+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_12 = { 1, NIM_NIL, "b" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_13 = {1, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_12};
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_14 = {0, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_10};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[2+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_16 = { 2, NIM_NIL, "> " };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_17 = {2, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_16};
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_18 = {0, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_10};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[8+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_19 = { 8, NIM_NIL, "schedule" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_20 = {8, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_19};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[80+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_21 = { 80, NIM_NIL, "==============================================================="
"=================" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_22 = {80, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_21};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[14+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_23 = { 14, NIM_NIL, "Got exception " };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_24 = {14, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_23};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[2+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_25 = { 2, NIM_NIL, ": " };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_26 = {2, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_25};
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_27 = {80, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_21};
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {}
static N_INLINE(void, nimDecWeakRef)(void* p) {	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) ((NI)((NU32)(((NI) (ptrdiff_t) (p))) - (NU32)(((NI) 4)))))).rc -= ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___kNpszSK9bonJaxhSTc9c9cCKw)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* dest) {	{
		if (!(*dest).filesystem) goto LA3_;
		nimDecWeakRef((*dest).filesystem);
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___4ViRAnT6CZeQCXJ9a9bZ5d4A)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ** dest, tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* src) {	{
		if (!(*dest)) goto LA3_;
		eqdestroy___kNpszSK9bonJaxhSTc9c9cCKw((*dest));
		nimRawDispose((*dest));
	}
	LA3_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___61f9c4QwTuBqt6IZB6V6HPQ)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* dest) {	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				if (!(*dest).p->data[colontmp_]) goto LA6_;
				nimDecWeakRef((*dest).p->data[colontmp_]);
			}
			LA6_: ;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && (*dest).p->allocator) {
 (*dest).p->allocator->dealloc((*dest).p->allocator, (*dest).p, ((*dest).p->cap * sizeof(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)) + sizeof(NI) + sizeof(void*)); }
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___5mNWyPlATqYO1X49aafjlqw)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* dest) {	{
		if (!(*dest).parent) goto LA3_;
		nimDecWeakRef((*dest).parent);
	}
	LA3_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).name));
	switch ((*dest).kind) {
	case ((tyEnum_FileKind__rqsxzaEqmlcOYhjylXOBbQ) 0):
	{
		eqdestroy___61f9c4QwTuBqt6IZB6V6HPQ((&(*dest).children));
	}
	break;
	default:
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).text));
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___IRi9akuRLCCwYQUuXGa9cYmA)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest, tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* src) {	{
		if (!(*dest)) goto LA3_;
		eqdestroy___5mNWyPlATqYO1X49aafjlqw((*dest));
		nimRawDispose((*dest));
	}
	LA3_: ;
	(*dest) = src;
}
static N_INLINE(void, nimIncRef)(void* p) {	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) ((NI)((NU32)(((NI) (ptrdiff_t) (p))) - (NU32)(((NI) 4)))))).rc += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, eq___IRi9akuRLCCwYQUuXGa9cYmA_2)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest, tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* src) {	{
		if (!src) goto LA3_;
		nimIncRef(src);
	}
	LA3_: ;
	{
		if (!(*dest)) goto LA7_;
		nimDecWeakRef((*dest));
	}
	LA7_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, eq___420KhbivyBN35wS61Ta50A)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* dest, tySequence__P3ZXR4R07tiqmqKWxuHhKQ src) {	NI T1_;
	NI colontmp_;
	T1_ = src.len;
	setLen__9cFY9csU2Vy6aqPrO9bDoi0NA((&(*dest)), T1_);
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T4_;
			T4_ = (*dest).len;
			if (!(colontmp_ < T4_)) goto LA3;
			{
				if (!src.p->data[colontmp_]) goto LA7_;
				nimIncRef(src.p->data[colontmp_]);
			}
			LA7_: ;
			{
				if (!(*dest).p->data[colontmp_]) goto LA11_;
				nimDecWeakRef((*dest).p->data[colontmp_]);
			}
			LA11_: ;
			(*dest).p->data[colontmp_] = src.p->data[colontmp_];
			colontmp_ += ((NI) 1);
		} LA3: ;
	}
}
static N_INLINE(void, popSafePoint)(void) {}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest) {	{
		if (!(*dest)) goto LA3_;
		nimDecWeakRef((*dest));
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA_2)(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g** dest) {	{
		if (!(*dest)) goto LA3_;
		eqdestroy___5mNWyPlATqYO1X49aafjlqw((*dest));
		nimRawDispose((*dest));
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*, file__YynSnpl3scimYAz0bfxHHw)(NimStringV2 name, tySequence__P3ZXR4R07tiqmqKWxuHhKQ children) {	tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* result;
	tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* file;
	NimStringV2 colontmpD_;
	tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* colontmpD__2;
	tySequence__P3ZXR4R07tiqmqKWxuHhKQ colontmpD__3;
	tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* child;
	tySequence__P3ZXR4R07tiqmqKWxuHhKQ colontmp_;
	TSafePoint TM__R8RUzYq41iOx0I9bZH5Nyrw_5;
{	result = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
	file = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	child = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
	colontmp_.len = 0; colontmp_.p = NIM_NIL;
	pushSafePoint(&TM__R8RUzYq41iOx0I9bZH5Nyrw_5);
	TM__R8RUzYq41iOx0I9bZH5Nyrw_5.status = setjmp(TM__R8RUzYq41iOx0I9bZH5Nyrw_5.context);
	if (TM__R8RUzYq41iOx0I9bZH5Nyrw_5.status == 0) {
		tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* T2_;
		T2_ = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
		T2_ = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*) nimNewObj(sizeof(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g));
		(*T2_).kind = ((tyEnum_FileKind__rqsxzaEqmlcOYhjylXOBbQ) 0);
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		eq___aBBXmHFBEivKqERloP6zmA_2((&colontmpD_), name);
		(*T2_).name = colontmpD_;
		colontmpD__2 = 0;
		eq___IRi9akuRLCCwYQUuXGa9cYmA_2(&colontmpD__2, NIM_NIL);
		(*T2_).parent = colontmpD__2;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		eq___420KhbivyBN35wS61Ta50A((&colontmpD__3), children);
		(*T2_).children = colontmpD__3;
		eqsink___IRi9akuRLCCwYQUuXGa9cYmA(&file, T2_);
		{
			NI i;
			NI L;
			NI T4_;
			eq___420KhbivyBN35wS61Ta50A((&colontmp_), (*file).children);
			i = ((NI) 0);
			T4_ = colontmp_.len;
			L = T4_;
			{
				while (1) {
					if (!(i < L)) goto LA6;
					eq___IRi9akuRLCCwYQUuXGa9cYmA_2(&child, colontmp_.p->data[i]);
					eq___IRi9akuRLCCwYQUuXGa9cYmA_2(&(*child).parent, file);
					i += ((NI) 1);
				} LA6: ;
			}
		}
		eqsink___IRi9akuRLCCwYQUuXGa9cYmA(&result, file);
		file = 0;
		popSafePoint();
		eqdestroy___61f9c4QwTuBqt6IZB6V6HPQ((&colontmp_));
		eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA(&child);
		eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA_2(&file);
		goto BeforeRet_;
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		eqdestroy___61f9c4QwTuBqt6IZB6V6HPQ((&colontmp_));
		eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA(&child);
		eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA_2(&file);
	}
	if (TM__R8RUzYq41iOx0I9bZH5Nyrw_5.status != 0) reraiseException();
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*, file__79c2zL1OCIGk68k8sohkCpw)(NimStringV2 name, NimStringV2 text) {	tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* T1_;
	result = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	T1_ = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
	T1_ = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*) nimNewObj(sizeof(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g));
	(*T1_).kind = ((tyEnum_FileKind__rqsxzaEqmlcOYhjylXOBbQ) 1);
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	eq___aBBXmHFBEivKqERloP6zmA_2((&colontmpD_), name);
	(*T1_).name = colontmpD_;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	eq___aBBXmHFBEivKqERloP6zmA_2((&colontmpD__2), text);
	(*T1_).text = colontmpD__2;
	eqsink___IRi9akuRLCCwYQUuXGa9cYmA(&result, T1_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ls__Mv3qRLY5H101D3bjLdhq7w)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* context) {	tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* child;
	tySequence__P3ZXR4R07tiqmqKWxuHhKQ colontmp_;
	TSafePoint TM__R8RUzYq41iOx0I9bZH5Nyrw_15;
	child = (tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*)0;
	colontmp_.len = 0; colontmp_.p = NIM_NIL;
	pushSafePoint(&TM__R8RUzYq41iOx0I9bZH5Nyrw_15);
	TM__R8RUzYq41iOx0I9bZH5Nyrw_15.status = setjmp(TM__R8RUzYq41iOx0I9bZH5Nyrw_15.context);
	if (TM__R8RUzYq41iOx0I9bZH5Nyrw_15.status == 0) {
		consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2(TM__R8RUzYq41iOx0I9bZH5Nyrw_17);
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ((*(*(*context).filesystem).current).name);
		{
			NI i;
			NI L;
			NI T3_;
			eq___420KhbivyBN35wS61Ta50A((&colontmp_), (*(*(*context).filesystem).current).children);
			i = ((NI) 0);
			T3_ = colontmp_.len;
			L = T3_;
			{
				while (1) {
					if (!(i < L)) goto LA5;
					eq___IRi9akuRLCCwYQUuXGa9cYmA_2(&child, colontmp_.p->data[i]);
					consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ((*child).name);
					i += ((NI) 1);
				} LA5: ;
			}
		}
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_18);
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		eqdestroy___61f9c4QwTuBqt6IZB6V6HPQ((&colontmp_));
		eqdestroy___9aazKO9czOOFRlQc9ap6wR9cgA(&child);
	}
	if (TM__R8RUzYq41iOx0I9bZH5Nyrw_15.status != 0) reraiseException();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___0p85KOjIVfNWTXEpPsMmNg)(tySequence__L2PnSpJoHRFiFGA8kZnz3A* dest) {	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				if (!(*dest).p->data[colontmp_]) goto LA6_;
				nimDecWeakRef((*dest).p->data[colontmp_]);
			}
			LA6_: ;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && (*dest).p->allocator) {
 (*dest).p->allocator->dealloc((*dest).p->allocator, (*dest).p, ((*dest).p->cap * sizeof(tyObject_ProcesscolonObjectType___Vh0UOZ7eoJ3cl9azhciMypA*)) + sizeof(NI) + sizeof(void*)); }
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___T9cM9cEzGIc4S3YkIu5hJtDA)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* dest) {	{
		if (!(*dest).context) goto LA3_;
		nimDecWeakRef((*dest).context);
	}
	LA3_: ;
	eqdestroy___0p85KOjIVfNWTXEpPsMmNg((&(*dest).processes));
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___hkiPLzq0zzi3PkuQM12MSQ)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ** dest, tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* src) {	{
		if (!(*dest)) goto LA3_;
		eqdestroy___T9cM9cEzGIc4S3YkIu5hJtDA((*dest));
		nimRawDispose((*dest));
	}
	LA3_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ*, initScheduler__ykdhg9awcGH79b40fvlTKNrg)(void) {	tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* result;
	tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* T1_;
	result = (tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ*)0;
	T1_ = (tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ*)0;
	T1_ = (tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ*) nimNewObj(sizeof(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ));
	eqsink___hkiPLzq0zzi3PkuQM12MSQ(&result, T1_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eq___4ViRAnT6CZeQCXJ9a9bZ5d4A_2)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ** dest, tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* src) {	{
		if (!src) goto LA3_;
		nimIncRef(src);
	}
	LA3_: ;
	{
		if (!(*dest)) goto LA7_;
		nimDecWeakRef((*dest));
	}
	LA7_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, schedule__RbdIHPlbvO5wzDKmqY9cxtQ)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* scheduler, tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* context) {	eq___4ViRAnT6CZeQCXJ9a9bZ5d4A_2(&(*scheduler).context, context);
	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_20);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GGAcUKitkAdlBRC7Qo4Bow)(tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ** dest) {	{
		if (!(*dest)) goto LA3_;
		eqdestroy___T9cM9cEzGIc4S3YkIu5hJtDA((*dest));
		nimRawDispose((*dest));
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___Iwx4PQuj2wDcj4AOFrZi0Q)(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ** dest) {	{
		if (!(*dest)) goto LA3_;
		eqdestroy___kNpszSK9bonJaxhSTc9c9cCKw((*dest));
		nimRawDispose((*dest));
	}
	LA3_: ;
}
N_NIMCALL(void, kmain)(void* header, NI b2) {	tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* context;
	tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* scheduler;
	TSafePoint TM__R8RUzYq41iOx0I9bZH5Nyrw_2;
	context = (tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ*)0;
	scheduler = (tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ*)0;
	pushSafePoint(&TM__R8RUzYq41iOx0I9bZH5Nyrw_2);
	TM__R8RUzYq41iOx0I9bZH5Nyrw_2.status = setjmp(TM__R8RUzYq41iOx0I9bZH5Nyrw_2.context);
	if (TM__R8RUzYq41iOx0I9bZH5Nyrw_2.status == 0) {
		tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ* T2_;
		tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA* T3_;
		tySequence__P3ZXR4R07tiqmqKWxuHhKQ T4_;
		tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ* T5_;
		vram__neZY9aEi0xFObl6yu5s62tQ = ((NIM_CHAR*) 753664);
		consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw = ((NI) 1);
		consoleY__rhX8TITk3JYo0RfIllnv1Q = ((NI) 0);
		screenClear__D9aD4l7GWk79biaBOEO4jNpA(((tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ) 15));
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_4);
		keyboardInstall();
		T2_ = (tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ*)0;
		T2_ = (tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ*) nimNewObj(sizeof(tyObject_ContextcolonObjectType___yZ186O8HB4Te9aQlcFhCqrQ));
		T3_ = (tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA*)0;
		T3_ = (tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA*) nimNewObj(sizeof(tyObject_FilesystemcolonObjectType___EEQcj7Z9bhiTiZgjGpnNDtA));
		T4_.len = 0; T4_.p = NIM_NIL;
		T4_.len = 2; T4_.p = (tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content*) newSeqPayload(2, sizeof(tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g*));
		T4_.p->data[0] = file__79c2zL1OCIGk68k8sohkCpw(TM__R8RUzYq41iOx0I9bZH5Nyrw_9, TM__R8RUzYq41iOx0I9bZH5Nyrw_11);
		T4_.p->data[1] = file__79c2zL1OCIGk68k8sohkCpw(TM__R8RUzYq41iOx0I9bZH5Nyrw_13, TM__R8RUzYq41iOx0I9bZH5Nyrw_14);
		(*T3_).root = file__YynSnpl3scimYAz0bfxHHw(TM__R8RUzYq41iOx0I9bZH5Nyrw_7, T4_);
		(*T2_).filesystem = T3_;
		eqsink___4ViRAnT6CZeQCXJ9a9bZ5d4A(&context, T2_);
		eq___IRi9akuRLCCwYQUuXGa9cYmA_2(&(*(*context).filesystem).current, (*(*context).filesystem).root);
		ls__Mv3qRLY5H101D3bjLdhq7w(context);
		T5_ = (tyObject_SchedulercolonObjectType___TnSxOiBsO0YiRhMYm8KXRQ*)0;
		T5_ = initScheduler__ykdhg9awcGH79b40fvlTKNrg();
		eqsink___hkiPLzq0zzi3PkuQM12MSQ(&scheduler, T5_);
		schedule__RbdIHPlbvO5wzDKmqY9cxtQ(scheduler, context);
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		eqdestroy___GGAcUKitkAdlBRC7Qo4Bow(&scheduler);
		eqdestroy___Iwx4PQuj2wDcj4AOFrZi0Q(&context);
	}
	if (TM__R8RUzYq41iOx0I9bZH5Nyrw_2.status != 0) reraiseException();
}
N_NIMCALL(void, install)(void) {	gdtInstall();
	idtInstall();
	isrsInstall();
	irqInstall();
}
N_NIMCALL(void, fault_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs) {	{
		if (!((NU32)((*regs).int_no) < (NU32)(((NU32) 32)))) goto LA3_;
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_22);
		consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2(TM__R8RUzYq41iOx0I9bZH5Nyrw_24);
		consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2(TM__R8RUzYq41iOx0I9bZH5Nyrw_26);
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[((*regs).int_no)- 0]);
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_27);
	}
	LA3_: ;
}

void PreMainInner(void) {
	stdlib_allocatorsInit000();
	unknown_isrsInit000();
	unknown_irqInit000();
}

int cmdCount;
char** cmdLine;
char** gEnv;
void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	stdlib_allocatorsDatInit000();
	systemInit000();
	(*inner)();
}

N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	eqdestroy___GF7fBXzeJgtHVCogYAjhKw(exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw);
	eqdestroy___s7Xz6U8AnHt9bxaO3CZFs2w(irq_routines__YajyNUbwz3nSWLLa5toz3g);
}
}

