/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "stdlib.h"
#include "string.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct AllocatorObj AllocatorObj;
typedef struct TNimType TNimType;
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___iJMelSyRU6RWIBySdiz9a5A)(AllocatorObj* a, NI size, NI alignment);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___La9bTlQ9c9b9cB1WAOyENIt6Ig)(AllocatorObj* a, void* p, NI size);
N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___3oPBf9aBNzv9c0DCHOew9a65Q)(AllocatorObj* a, void* p, NI oldSize, NI newSize);
AllocatorObj* localAllocator__Fo4FsHewuC4VzDNrMpf3Og;
AllocatorObj* sharedAllocator__14UnoPGASR4x3NgNJ5Y5lA;
AllocatorObj allocatorStorage__9abMNjDlLVxVrfWZARGJwzw;
TNimType NTI__d9aje06sbOkiVogdUrGOkfQ_;
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___iJMelSyRU6RWIBySdiz9a5A)(AllocatorObj* a, NI size, NI alignment) {	void* result;
	result = (void*)0;
	result = malloc(((size_t) (size)));
	nimZeroMem(result, ((NI) (size)));
	(*a).allocCount += ((NI) 1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___La9bTlQ9c9b9cB1WAOyENIt6Ig)(AllocatorObj* a, void* p, NI size) {	free(p);
	(*a).deallocCount += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void*, colonanonymous___3oPBf9aBNzv9c0DCHOew9a65Q)(AllocatorObj* a, void* p, NI oldSize, NI newSize) {	void* result;
	result = (void*)0;
	result = realloc(p, ((size_t) (newSize)));
	nimZeroMem(((void*) ((NI)((NU32)(((NI) (ptrdiff_t) (result))) + (NU32)(oldSize)))), ((NI) ((NI)(newSize - oldSize))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(AllocatorObj*, getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw)(void) {	AllocatorObj* result;
	result = (AllocatorObj*)0;
	result = localAllocator__Fo4FsHewuC4VzDNrMpf3Og;
	{
		if (!(result == NIM_NIL)) goto LA3_;
		result = (&allocatorStorage__9abMNjDlLVxVrfWZARGJwzw);
		(*result).alloc = colonanonymous___iJMelSyRU6RWIBySdiz9a5A;
		(*result).dealloc = colonanonymous___La9bTlQ9c9b9cB1WAOyENIt6Ig;
		(*result).realloc = colonanonymous___3oPBf9aBNzv9c0DCHOew9a65Q;
		(*result).deallocAll = NIM_NIL;
		(*result).flags = 3;
		(*result).name = "nim_local";
		localAllocator__Fo4FsHewuC4VzDNrMpf3Og = result;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsInit000)(void) {
{
	TFrame FR_; FR_.len = 0;
	allocatorStorage__9abMNjDlLVxVrfWZARGJwzw.m_type = (&NTI__d9aje06sbOkiVogdUrGOkfQ_);
}
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_allocatorsDatInit000)(void) {
NTI__d9aje06sbOkiVogdUrGOkfQ_.destructor = (void*)NIM_NIL; NTI__d9aje06sbOkiVogdUrGOkfQ_.size = sizeof(AllocatorObj); NTI__d9aje06sbOkiVogdUrGOkfQ_.name = "|stdlib.allocators.AllocatorObj|";
}

