/* Generated by Nim Compiler v1.3.1 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <signal.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct Exception Exception;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct TSafePoint TSafePoint;
typedef struct GcFrameHeader GcFrameHeader;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct TNimType TNimType;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_NIMCALL_PTR(void, tyProc__NFmM6mqUOVW3cJg4yvk8Fw) (Exception* e);
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef N_NIMCALL_PTR(void, tyProc__W6IXMh2CA4X1rFYGjUb4yg) (NimStringV2 msg);
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct TNimType {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
};
typedef N_NIMCALL_PTR(void, tyProc__4SVlZZPmetqBimNsH9cHcOA) (void* p);
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
typedef N_NOCONV_PTR(void, tyProc__lfH2drpqP9aSEAAjWgrYv8Q) (int a);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, initStackBottom)(void);
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign);
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw)(NCSTRING data);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p);
N_LIB_PRIVATE N_NOCONV(void, deallocSharedImpl__lmwgHsdhTsrQaepFju8wew)(void* p);
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__lmwgHsdhTsrQaepFju8wew_2)(void* p);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len);
N_LIB_PRIVATE N_NOCONV(void*, allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA)(NI size);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__1Sx5YIRdVWZ4weqfKjYzWA_2)(NI size);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(size_t, nimCStrLen)(NCSTRING a);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eq___rR9boD7urcxl7uyUtE46AOA)(Exception** dest, Exception* src);
static N_INLINE(void, nimIncRef)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ)(NCSTRING msg);
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s);
N_LIB_PRIVATE N_NIMCALL(void, registerSignalHandler__amVlU9ajqZ06ujoesRBHcDg)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___rR9boD7urcxl7uyUtE46AOA_2)(Exception** dest, Exception* src);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE NI nim_program_result;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg;
N_LIB_PRIVATE tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__kZNaA7u1MfSW5ZeoGvw8xg;
N_LIB_PRIVATE tyProc__NFmM6mqUOVW3cJg4yvk8Fw unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw;
N_LIB_PRIVATE Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A;
N_LIB_PRIVATE TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
N_LIB_PRIVATE TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
N_LIB_PRIVATE GcFrameHeader* gcFramePtr__ot48iojqko9aFxGhyjjjVaA;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg onUnhandledException__bFrawQlTKZhLweDD36j9b8g;
N_LIB_PRIVATE NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
static N_INLINE(void, initStackBottom)(void) {
}
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__lmwgHsdhTsrQaepFju8wew_2)(void* p) {
	free(p);
}
N_LIB_PRIVATE N_NOCONV(void, deallocSharedImpl__lmwgHsdhTsrQaepFju8wew)(void* p) {
	deallocImpl__lmwgHsdhTsrQaepFju8wew_2(p);
}
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p) {
	deallocSharedImpl__lmwgHsdhTsrQaepFju8wew(p);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest) {
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest).p);
 (*dest).p = NIM_NIL; (*dest).len = 0; }
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src) {
	if ((*dest).len && (*dest).p != src.p) {	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest);
	}
(*dest).len = src.len; (*dest).p = src.p;
}
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__1Sx5YIRdVWZ4weqfKjYzWA_2)(NI size) {
	void* result;
	result = (void*)0;
	// result = calloc(((size_t) (size)), ((size_t) 1));
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA)(NI size) {
	void* result;
	result = (void*)0;
	result = alloc0Impl__1Sx5YIRdVWZ4weqfKjYzWA_2(size);
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len) {
	NimStringV2 result;
	NI colontmpD_;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	colontmpD_ = (NI)0;
	{
		if (!(len <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = NIM_NIL;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStrPayload* p;
		void* T6_;
		T6_ = (void*)0;
		T6_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)((NI)(len + ((NI) 1)) + ((NI) 4)))));
		p = ((NimStrPayload*) (T6_));
		(*p).cap = len;
		{
			if (!(((NI) 0) < len)) goto LA9_;
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*p).data[((NI) 0)]))), ((void*) (str)), ((NI) (len)));
		}
		LA9_: ;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD_ = len;
		result.len = colontmpD_;
		result.p = p;
	}
	LA1_: ;
	return result;
}
static N_INLINE(size_t, nimCStrLen)(NCSTRING a) {
	size_t result;
	result = (size_t)0;
	result = strlen(a);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str) {
	NimStringV2 result;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(((void*) (str)) == NIM_NIL)) goto LA3_;
		result = toNimStr(str, ((NI) 0));
	}
	goto LA1_;
	LA3_: ;
	{
		result = toNimStr(str, (str ? nimCStrLen(str) : 0));
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc += ((NI) 8);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
	free(((void*) (T1_)));
}
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p) {
	void* d;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	d = (*(*((TNimType**) (p)))).destructor;
	{
		if (!!((d == NIM_NIL))) goto LA3_;
		((tyProc__4SVlZZPmetqBimNsH9cHcOA) (d))(p);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	nimRawDispose(p);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eq___rR9boD7urcxl7uyUtE46AOA)(Exception** dest, Exception* src) {
	{
		if (!src) goto LA3_;
		nimIncRef(src);
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest));
		if (!T7_) goto LA8_;
		nimDestroyAndDispose((*dest));
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, popCurrentException)(void) {
	eq___rR9boD7urcxl7uyUtE46AOA(&currException__9bVPeDJlYTi9bQApZpfH8wjg, (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);
}
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s) {
	int T1_;
	int T2_;
	T1_ = (int)0;
	T1_ = fwrite(((void*) (s)), ((size_t) 1), ((size_t) ((s ? nimCStrLen(s) : 0))), f);
	(void)(T1_);
	T2_ = (int)0;
	T2_ = fflush(f);
	(void)(T2_);
}
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ)(NCSTRING msg) {
	rawWrite(stderr, msg);
}
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw)(NCSTRING data) {
	NimStringV2 colontmpD_;
	NIM_BOOL toWrite;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	toWrite = NIM_TRUE;
	{
		NimStringV2 T7_;
		if (!!((errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A == NIM_NIL))) goto LA4_;
		T7_.len = 0; T7_.p = NIM_NIL;
		T7_ = cstrToNimstr(data);
		eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T7_);
		errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A(colontmpD_);
		toWrite = NIM_FALSE;
		if (NIM_UNLIKELY(*nimErr_)) {
			LA6_:;
			{
				*nimErr_ = NIM_FALSE;
				popCurrentException();
				LA9_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA4_: ;
	{
		if (!toWrite) goto LA13_;
		writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ(data);
	}
	LA13_: ;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign) {
	NCSTRING msg;
	msg = (NCSTRING)0;
	{
		if (!(sign == SIGINT)) goto LA3_;
		msg = "SIGINT: Interrupted by Ctrl-C.\012";
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(sign == SIGSEGV)) goto LA6_;
		msg = "SIGSEGV: Illegal storage access. (Attempt to read from nil\?)\012";
	}
	goto LA1_;
	LA6_: ;
	{
		if (!(sign == SIGABRT)) goto LA9_;
		msg = "SIGABRT: Abnormal termination.\012";
	}
	goto LA1_;
	LA9_: ;
	{
		if (!(sign == SIGFPE)) goto LA12_;
		msg = "SIGFPE: Arithmetic error.\012";
	}
	goto LA1_;
	LA12_: ;
	{
		if (!(sign == SIGILL)) goto LA15_;
		msg = "SIGILL: Illegal operation.\012";
	}
	goto LA1_;
	LA15_: ;
	{
		if (!NIM_FALSE) goto LA18_;
		msg = "SIGBUS: Illegal storage access. (Attempt to read from nil\?)\012";
	}
	goto LA1_;
	LA18_: ;
	{
		{
			msg = "unknown signal\012";
		}
	}
	LA1_: ;
	showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw(msg);
	exit(((NI) 1));
}
N_LIB_PRIVATE N_NIMCALL(void, registerSignalHandler__amVlU9ajqZ06ujoesRBHcDg)(void) {
	tyProc__lfH2drpqP9aSEAAjWgrYv8Q T1_;
	tyProc__lfH2drpqP9aSEAAjWgrYv8Q T2_;
	tyProc__lfH2drpqP9aSEAAjWgrYv8Q T3_;
	tyProc__lfH2drpqP9aSEAAjWgrYv8Q T4_;
	tyProc__lfH2drpqP9aSEAAjWgrYv8Q T5_;
	T1_ = (tyProc__lfH2drpqP9aSEAAjWgrYv8Q)0;
	T1_ = signal(SIGINT, signalHandler);
	T2_ = (tyProc__lfH2drpqP9aSEAAjWgrYv8Q)0;
	T2_ = signal(SIGSEGV, signalHandler);
	T3_ = (tyProc__lfH2drpqP9aSEAAjWgrYv8Q)0;
	T3_ = signal(SIGABRT, signalHandler);
	T4_ = (tyProc__lfH2drpqP9aSEAAjWgrYv8Q)0;
	T4_ = signal(SIGFPE, signalHandler);
	T5_ = (tyProc__lfH2drpqP9aSEAAjWgrYv8Q)0;
	T5_ = signal(SIGILL, signalHandler);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, mnewString)(NI len) {
	NimStringV2 result;
	NI colontmpD_;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	colontmpD_ = (NI)0;
	{
		if (!(len <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = NIM_NIL;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStrPayload* p;
		void* T6_;
		T6_ = (void*)0;
		T6_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)((NI)(len + ((NI) 1)) + ((NI) 4)))));
		p = ((NimStrPayload*) (T6_));
		(*p).cap = len;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD_ = len;
		result.len = colontmpD_;
		result.p = p;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s) {
	{
		NIM_BOOL T3_;
		NimStrPayload* oldP;
		void* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == NIM_NIL));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		oldP = (*s).p;
		T7_ = (void*)0;
		T7_ = allocShared0Impl__1Sx5YIRdVWZ4weqfKjYzWA(((NI) ((NI)((NI)((*s).len + ((NI) 1)) + ((NI) 4)))));
		(*s).p = ((NimStrPayload*) (T7_));
		(*(*s).p).cap = (*s).len;
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*s).p).data[((NI) 0)]))), ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((NI)((*s).len + ((NI) 1)))));
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	result = mnewString(((NI) 1));
	nimPrepareStrMutationV2((&result));
	result.p->data[((NI) 0)] = x;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw)(Exception* e) {
	{
		if (!!((unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw == NIM_NIL))) goto LA3_;
		unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw(e);
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___rR9boD7urcxl7uyUtE46AOA_2)(Exception** dest, Exception* src) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimInErrorMode__759bT87luu8XGcbkw13FUjA;
		if (!(T3_)) goto LA4_;
		T3_ = !((currException__9bVPeDJlYTi9bQApZpfH8wjg == NIM_NIL));
		LA4_: ;
		if (!T3_) goto LA5_;
		reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw(currException__9bVPeDJlYTi9bQApZpfH8wjg);
		eqsink___rR9boD7urcxl7uyUtE46AOA_2(&currException__9bVPeDJlYTi9bQApZpfH8wjg, NIM_NIL);
		exit(((NI) 1));
	}
	LA5_: ;
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
}
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
{
	initStackBottom();
	registerSignalHandler__amVlU9ajqZ06ujoesRBHcDg();
}
}

