/* Generated by Nim Compiler v1.3.1 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__pGKepcbONSu6mlrtFDHLIQ[130001];
typedef NU8 tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs, void* ClE_0);
void* ClE_0;
} tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ;
typedef tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ tyArray__go59cYo0lifoWWnigBty2Tg[16];
typedef NimStringV2 tyArray__c2QNJmc34bMEk131Zq7ttQ[32];
N_LIB_PRIVATE N_NIMCALL(void, install)(void);
N_LIB_PRIVATE N_NIMCALL(void, consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ)(NimStringV2 a);
N_LIB_PRIVATE N_NIMCALL(void, gdtInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, idtInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, isrsInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, irqInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, keyboardInstall)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, kmain)(void* header, NI b2);
N_LIB_PRIVATE N_NIMCALL(void, screenClear__D9aD4l7GWk79biaBOEO4jNpA)(tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ color);
N_LIB_PRIVATE N_NIMCALL(void, fault_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___s7Xz6U8AnHt9bxaO3CZFs2w)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GF7fBXzeJgtHVCogYAjhKw)(NimStringV2* dest);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_2 = { 7 | NIM_STRLIT_FLAG, "install" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_3 = {7, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_2};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__R8RUzYq41iOx0I9bZH5Nyrw_4 = { 7 | NIM_STRLIT_FLAG, "welcome" };
static const NimStringV2 TM__R8RUzYq41iOx0I9bZH5Nyrw_5 = {7, (NimStrPayload*)&TM__R8RUzYq41iOx0I9bZH5Nyrw_4};
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_CHAR* vram__neZY9aEi0xFObl6yu5s62tQ;
extern NI consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw;
extern NI consoleY__rhX8TITk3JYo0RfIllnv1Q;
extern tyArray__go59cYo0lifoWWnigBty2Tg irq_routines__YajyNUbwz3nSWLLa5toz3g;
extern tyArray__c2QNJmc34bMEk131Zq7ttQ exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, install)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	gdtInstall();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	idtInstall();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	isrsInstall();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	irqInstall();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	keyboardInstall();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, kmain)(void* header, NI b2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	vram__neZY9aEi0xFObl6yu5s62tQ = ((NIM_CHAR*) 753664);
	consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw = ((NI) 1);
	consoleY__rhX8TITk3JYo0RfIllnv1Q = ((NI) 0);
	screenClear__D9aD4l7GWk79biaBOEO4jNpA(((tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ) 15));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	install();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	  __asm__ __volatile__ ("sti");
  
	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__R8RUzYq41iOx0I9bZH5Nyrw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, fault_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs) {
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	systemInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	eqdestroy___s7Xz6U8AnHt9bxaO3CZFs2w(irq_routines__YajyNUbwz3nSWLLa5toz3g);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___GF7fBXzeJgtHVCogYAjhKw(exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

