/* Generated by Nim Compiler v1.3.1 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NU8 tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ;
N_LIB_PRIVATE N_NIMCALL(void, writeString__fBz9cf9a79cF1auYe4i9bcV57A)(NimStringV2 a, NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, writeChar__3rPw4Pk9bRnz0VpOSKYyS8g)(NIM_CHAR a, NI x, NI y);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE NIM_CHAR* vram__neZY9aEi0xFObl6yu5s62tQ;
N_LIB_PRIVATE NI consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw;
N_LIB_PRIVATE NI consoleY__rhX8TITk3JYo0RfIllnv1Q;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
N_LIB_PRIVATE N_NIMCALL(void, writeChar__3rPw4Pk9bRnz0VpOSKYyS8g)(NIM_CHAR a, NI x, NI y) {
	vram__neZY9aEi0xFObl6yu5s62tQ[((NI)((NI)(((NI) 160) * x) + y))- 0] = a;
	vram__neZY9aEi0xFObl6yu5s62tQ[((NI)((NI)((NI)(((NI) 160) * x) + y) + ((NI) 1)))- 0] = 241;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, writeString__fBz9cf9a79cF1auYe4i9bcV57A)(NimStringV2 a, NI x, NI y) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI b;
		NI colontmp_;
		NI i;
		b = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = a.len;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < colontmp_)) goto LA3;
				b = i;
				writeChar__3rPw4Pk9bRnz0VpOSKYyS8g(a.p->data[b], x, (NI)(y + (NI)(b * ((NI) 2))));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i += ((NI) 1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ)(NimStringV2 a) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	writeString__fBz9cf9a79cF1auYe4i9bcV57A(a, consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw, consoleY__rhX8TITk3JYo0RfIllnv1Q);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw += ((NI) 1);
	consoleY__rhX8TITk3JYo0RfIllnv1Q = ((NI) 0);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2)(NimStringV2 a) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	writeString__fBz9cf9a79cF1auYe4i9bcV57A(a, consoleX__ZQwLP6p9bSkd9aDpG9cvzNC9bw, consoleY__rhX8TITk3JYo0RfIllnv1Q);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	consoleY__rhX8TITk3JYo0RfIllnv1Q += a.len;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, screenClear__D9aD4l7GWk79biaBOEO4jNpA)(tyEnum_TVGAColor__lyxjcObSwMKkPqLxZG6SoQ color) {
	NIM_CHAR c;
	NI i;
	c = 95;
	i = ((NI) 0);
	{
		while (1) {
			if (!(i <= ((NI) 4000))) goto LA2;
			vram__neZY9aEi0xFObl6yu5s62tQ[(i)- 0] = c;
			vram__neZY9aEi0xFObl6yu5s62tQ[((NI)(i + ((NI) 1)))- 0] = 255;
			i += ((NI) 2);
		} LA2: ;
	}
}
