/* Generated by Nim Compiler v1.3.1 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_Idt_entry__3ov69cd9cCyE4k5VooD9cPfOA tyObject_Idt_entry__3ov69cd9cCyE4k5VooD9cPfOA;
typedef struct tyObject_Idt_ptr__9apruuJBpIS3tat1Pythx0A tyObject_Idt_ptr__9apruuJBpIS3tat1Pythx0A;
struct __attribute__((__packed__)) tyObject_Idt_entry__3ov69cd9cCyE4k5VooD9cPfOA {
NU16 base_low;
NU16 sel;
NU8 always0;
NU8 flags;
NU16 base_high;
};
typedef tyObject_Idt_entry__3ov69cd9cCyE4k5VooD9cPfOA tyArray__CFLR9bqHhihjfVzmtH7jilQ[256];
struct __attribute__((__packed__)) tyObject_Idt_ptr__9apruuJBpIS3tat1Pythx0A {
NU16 limit;
NU32 base;
};
N_LIB_PRIVATE N_NIMCALL(void, idtInstall)(void);
N_NIMCALL(void, memset)(void* begin, NU8 value, NU32 size);
N_NIMCALL(void, idt_load)(void);
N_LIB_PRIVATE tyArray__CFLR9bqHhihjfVzmtH7jilQ idt__euYbwzV2omu8FqllndOzyQ;
N_LIB_PRIVATE tyObject_Idt_ptr__9apruuJBpIS3tat1Pythx0A idtp;
N_LIB_PRIVATE N_NIMCALL(void, idtInstall)(void) {
	NU8* ptr_idt;
	idtp.limit = (NU16)((NU16)(((NU16) (((NI) 2048)))) - (NU16)(((NU16) 1)));
	idtp.base = ((NU32) (ptrdiff_t) (idt__euYbwzV2omu8FqllndOzyQ));
	ptr_idt = ((NU8*) (idt__euYbwzV2omu8FqllndOzyQ));
	memset(((void*) (ptr_idt)), ((NU8) 0), ((NU32) (((NI) 2048))));
	idt_load();
}
N_LIB_PRIVATE N_NIMCALL(void, idtSetGate__uB9aAbzjB9bRgxmfLMWFiDxw)(NU8 num, NU32 base, NU16 sel, NU8 flags) {
	idt__euYbwzV2omu8FqllndOzyQ[(num)- 0].base_low = ((NU16) ((NU32)(base & ((NU32) 65535))));
	idt__euYbwzV2omu8FqllndOzyQ[(num)- 0].base_high = ((NU16) ((NU32)((NU32)((NU32)(base) >> (NU32)(((NI) 16))) & ((NU32) 65535))));
	idt__euYbwzV2omu8FqllndOzyQ[(num)- 0].sel = sel;
	idt__euYbwzV2omu8FqllndOzyQ[(num)- 0].always0 = ((NU8) 0);
	idt__euYbwzV2omu8FqllndOzyQ[(num)- 0].flags = flags;
}
