/* Generated by Nim Compiler v1.3.1 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs, void* ClE_0);
void* ClE_0;
} tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ;
typedef tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ tyArray__go59cYo0lifoWWnigBty2Tg[16];
struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg {
NU32 gs;
NU32 fs;
NU32 es;
NU32 ds;
NU32 edi;
NU32 esi;
NU32 ebp;
NU32 esp;
NU32 ebx;
NU32 edx;
NU32 ecx;
NU32 eax;
NU32 int_no;
NU32 err_code;
NU32 eip;
NU32 cs;
NU32 eflags;
NU32 useresp;
NU32 ss;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
typedef N_CLOSURE_PTR(void, TM__0xRZp3H9cHgeuOhm7vEmXCQ_2) (tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs);
extern void irq0();
extern void irq1();
extern void irq2();
extern void irq3();
extern void irq4();
extern void irq5();
extern void irq6();
extern void irq7();
extern void irq8();
extern void irq9();
extern void irq10();
extern void irq11();
extern void irq12();
extern void irq13();
extern void irq14();
extern void irq15();

N_LIB_PRIVATE N_NIMCALL(void, installHandler)(NI irq, tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ handler);
N_LIB_PRIVATE N_NIMCALL(void, irqInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, irqRemap__L2csWl1nQ3kCSSiMCwVByw)(void);
N_LIB_PRIVATE N_NIMCALL(void, outb__WHsX9cRAb9ansZ7pOaHMylNw)(NU16 port, NU8 value);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, idtSetGate__uB9aAbzjB9bRgxmfLMWFiDxw)(NU8 num, NU32 base, NU16 sel, NU8 flags);
N_LIB_PRIVATE N_NIMCALL(NU32, getIrq__nj7VDsgSqKXMeJByIbMM9cQ)(NI i);
N_LIB_PRIVATE N_NIMCALL(void, irq_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs);
N_LIB_PRIVATE N_NIMCALL(void, eq___GpC8qBFt3byX9a0BZ9cIhXPQ)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest, tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ src);
static N_INLINE(void, nimIncRef)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___yStHfWBMzgYDVMhG4jeUEA)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest);
N_LIB_PRIVATE tyArray__go59cYo0lifoWWnigBty2Tg irq_routines__YajyNUbwz3nSWLLa5toz3g;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
N_LIB_PRIVATE N_NIMCALL(void, installHandler)(NI irq, tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ handler) {
	  irq_routines__YajyNUbwz3nSWLLa5toz3g[irq] = handler;
  
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, irqRemap__L2csWl1nQ3kCSSiMCwVByw)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 32), ((NU8) 17));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 160), ((NU8) 17));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 33), ((NU8) 32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 161), ((NU8) 40));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 33), ((NU8) 4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 161), ((NU8) 2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 33), ((NU8) 1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 161), ((NU8) 1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 33), ((NU8) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 161), ((NU8) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, getIrq__nj7VDsgSqKXMeJByIbMM9cQ)(NI i) {
	NU32 result;
	result = (NU32)0;
	  switch(i) {
  case 0:
    result = irq0;
    break;
  case 1:
    result = irq1;
    break;
  case 2:
    result = irq2;
    break;
  case 3:
    result = irq3;
    break;
  case 4:
    result = irq4;
    break;
  case 5:
    result = irq5;
    break;
  case 6:
    result = irq6;
    break;
  case 7:
    result = irq7;
    break;
  case 8:
    result = irq8;
    break;
  case 9:
    result = irq9;
    break;
  case 10:
    result = irq10;
    break;
  case 11:
    result = irq11;
    break;
  case 12:
    result = irq12;
    break;
  case 13:
    result = irq13;
    break;
  case 14:
    result = irq14;
    break;
  case 15:
    result = irq15;
    break;
  }
  
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, irqInstall)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	irqRemap__L2csWl1nQ3kCSSiMCwVByw();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				NU32 T4_;
				if (!(res <= ((NI) 15))) goto LA3;
				i = res;
				T4_ = (NU32)0;
				T4_ = getIrq__nj7VDsgSqKXMeJByIbMM9cQ(i);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				idtSetGate__uB9aAbzjB9bRgxmfLMWFiDxw(((NU8) ((NI)(((NI) 32) + i))), T4_, ((NU16) (((NI) 8))), ((NU8) (((NI) 142))));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				res += ((NI) 1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc += ((NI) 8);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eq___GpC8qBFt3byX9a0BZ9cIhXPQ)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest, tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ src) {
	{
		if (!src.ClE_0) goto LA3_;
		nimIncRef(src.ClE_0);
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest).ClE_0);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose((*dest).ClE_0);
	}
	LA8_: ;
	(*dest).ClE_0 = src.ClE_0;
	(*dest).ClP_0 = src.ClP_0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___yStHfWBMzgYDVMhG4jeUEA)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).ClE_0);
		(*dest).ClE_0 = NIM_NIL;
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, irq_handler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs) {
	tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ handler;
	NU32 irqIndex;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	irqIndex = (NU32)((NU32)((*regs).int_no) - (NU32)(((NU32) 32)));
	eq___GpC8qBFt3byX9a0BZ9cIhXPQ((&handler), irq_routines__YajyNUbwz3nSWLLa5toz3g[(irqIndex)- 0]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!!((handler.ClP_0 == 0))) goto LA4_;
		handler.ClE_0? handler.ClP_0(regs, handler.ClE_0):((TM__0xRZp3H9cHgeuOhm7vEmXCQ_2)(handler.ClP_0))(regs);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA4_: ;
	{
		if (!((NU32)(((NU32) (((NI) 40)))) <= (NU32)((NU32)((NU32)(irqIndex) + (NU32)(((NU32) 32)))))) goto LA8_;
		outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 160), ((NU8) 32));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA8_: ;
	outb__WHsX9cRAb9ansZ7pOaHMylNw(((NU16) 32), ((NU8) 32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___yStHfWBMzgYDVMhG4jeUEA((&handler));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___s7Xz6U8AnHt9bxaO3CZFs2w)(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			if (!(colontmp_ < ((NI) 16))) goto LA2;
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = nimDecRefIsLast(dest[(colontmp_)- 0].ClE_0);
				if (!T5_) goto LA6_;
				nimDestroyAndDispose(dest[(colontmp_)- 0].ClE_0);
				dest[(colontmp_)- 0].ClE_0 = NIM_NIL;
			}
			LA6_: ;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
}
