/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_Gdt_entry__rYmtzj3lfwc3ophQ0xuqWw tyObject_Gdt_entry__rYmtzj3lfwc3ophQ0xuqWw;
typedef struct tyObject_Gdt_ptr__WOInRIC82zhiZVhkOumHsg tyObject_Gdt_ptr__WOInRIC82zhiZVhkOumHsg;
struct __attribute__((__packed__)) tyObject_Gdt_entry__rYmtzj3lfwc3ophQ0xuqWw {
NU16 limit_low;
NU16 base_low;
NU8 base_middle;
NU8 access;
NU8 granularity;
NU8 base_high;
};
typedef tyObject_Gdt_entry__rYmtzj3lfwc3ophQ0xuqWw tyArray__n2XqDndrEG9cU2Z9bR3kDB7w[3];
struct __attribute__((__packed__)) tyObject_Gdt_ptr__WOInRIC82zhiZVhkOumHsg {
NU16 limit;
NU32 base;
};
N_NIMCALL(void, gdtInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, gdtSetGate__qt9cJWBWVWXmyLS5hXFbR1Q)(NI num, NU32 base, NU32 limit, NU8 access, NU8 gran);
N_NIMCALL(void, gdt_flush)(void);
tyArray__n2XqDndrEG9cU2Z9bR3kDB7w gdt__DbLg3puavgQLW3LzN6gCJA;
tyObject_Gdt_ptr__WOInRIC82zhiZVhkOumHsg gp;
N_LIB_PRIVATE N_NIMCALL(void, gdtSetGate__qt9cJWBWVWXmyLS5hXFbR1Q)(NI num, NU32 base, NU32 limit, NU8 access, NU8 gran) {	gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].base_low = ((NU16) ((NU32)(base & ((NU32) 65535))));
	gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].base_middle = ((NU8) ((NU32)((NU32)((NU32)(base) >> (NU32)(((NI) 16))) & ((NU32) 255))));
	gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].base_high = ((NU8) ((NU32)((NU32)((NU32)(base) >> (NU32)(((NI) 24))) & ((NU32) 255))));
	gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].limit_low = ((NU16) ((NU32)(limit & ((NU32) 65535))));
	gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].granularity = ((NU8) ((NU32)((NU32)((NU32)(limit) >> (NU32)(((NI) 16))) & ((NU32) 15))));
	gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].granularity = (NU8)(gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].granularity | (NU8)(gran & ((NU8) 240)));
	gdt__DbLg3puavgQLW3LzN6gCJA[(num)- 0].access = access;
}
N_NIMCALL(void, gdtInstall)(void) {	gp.limit = ((NU16) (((NI) 23)));
	gp.base = ((NU32) (ptrdiff_t) (gdt__DbLg3puavgQLW3LzN6gCJA));
	gdtSetGate__qt9cJWBWVWXmyLS5hXFbR1Q(((NI) 0), ((NU32) 0), ((NU32) 0), ((NU8) 0), ((NU8) 0));
	gdtSetGate__qt9cJWBWVWXmyLS5hXFbR1Q(((NI) 1), ((NU32) 0), ((NU32) (IL64(4294967295))), ((NU8) 154), ((NU8) 207));
	gdtSetGate__qt9cJWBWVWXmyLS5hXFbR1Q(((NI) 2), ((NU32) 0), ((NU32) (IL64(4294967295))), ((NU8) 146), ((NU8) 207));
	gdt_flush();
}
