/* Generated by Nim Compiler v1.3.1 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(void, keyboardHandler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs);
N_LIB_PRIVATE N_NIMCALL(void, consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ)(NimStringV2 a);
N_LIB_PRIVATE N_NIMCALL(NU8, inb__HQ0Xhmit0RzG5MHuATBKcQ)(NU16 port);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, scanCodeToAscii__mfmfNCzuyizG3Gp9a8dDflg)(NU8 scancode);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x);
N_LIB_PRIVATE N_NIMCALL(void, consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2)(NimStringV2 a);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, keyboardInstall)(void);
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__ZrVepqz9a1O4OWN5tc4Iqnw_2 = { 9 | NIM_STRLIT_FLAG, "keyboard2" };
static const NimStringV2 TM__ZrVepqz9a1O4OWN5tc4Iqnw_3 = {9, (NimStrPayload*)&TM__ZrVepqz9a1O4OWN5tc4Iqnw_2};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__ZrVepqz9a1O4OWN5tc4Iqnw_4 = { 24 | NIM_STRLIT_FLAG, "Unrecognized scancode..." };
static const NimStringV2 TM__ZrVepqz9a1O4OWN5tc4Iqnw_5 = {24, (NimStrPayload*)&TM__ZrVepqz9a1O4OWN5tc4Iqnw_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__ZrVepqz9a1O4OWN5tc4Iqnw_6 = { 17 | NIM_STRLIT_FLAG, "GOT DEBUG SIGNAL!" };
static const NimStringV2 TM__ZrVepqz9a1O4OWN5tc4Iqnw_7 = {17, (NimStrPayload*)&TM__ZrVepqz9a1O4OWN5tc4Iqnw_6};
static const NimStringV2 TM__ZrVepqz9a1O4OWN5tc4Iqnw_8 = {24, (NimStrPayload*)&TM__ZrVepqz9a1O4OWN5tc4Iqnw_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__ZrVepqz9a1O4OWN5tc4Iqnw_9 = { 8 | NIM_STRLIT_FLAG, "keyboard" };
static const NimStringV2 TM__ZrVepqz9a1O4OWN5tc4Iqnw_10 = {8, (NimStrPayload*)&TM__ZrVepqz9a1O4OWN5tc4Iqnw_9};
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, scanCodeToAscii__mfmfNCzuyizG3Gp9a8dDflg)(NU8 scancode) {
	NIM_CHAR result;
{	result = (NIM_CHAR)0;
	switch (scancode) {
	case ((NI) 0):
	{
		result = 0;
		goto BeforeRet_;
	}
	break;
	case ((NI) 14):
	{
		result = 8;
		goto BeforeRet_;
	}
	break;
	case ((NI) 16):
	{
		result = 113;
		goto BeforeRet_;
	}
	break;
	case ((NI) 17):
	{
		result = 119;
		goto BeforeRet_;
	}
	break;
	case ((NI) 18):
	{
		result = 101;
		goto BeforeRet_;
	}
	break;
	case ((NI) 19):
	{
		result = 114;
		goto BeforeRet_;
	}
	break;
	case ((NI) 20):
	{
		result = 116;
		goto BeforeRet_;
	}
	break;
	case ((NI) 21):
	{
		result = 121;
		goto BeforeRet_;
	}
	break;
	case ((NI) 22):
	{
		result = 117;
		goto BeforeRet_;
	}
	break;
	case ((NI) 23):
	{
		result = 105;
		goto BeforeRet_;
	}
	break;
	case ((NI) 24):
	{
		result = 111;
		goto BeforeRet_;
	}
	break;
	case ((NI) 25):
	{
		result = 112;
		goto BeforeRet_;
	}
	break;
	case ((NI) 57):
	{
		result = 32;
		goto BeforeRet_;
	}
	break;
	default:
	{
		result = 0;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, keyboardHandler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NU8 scancode;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ZrVepqz9a1O4OWN5tc4Iqnw_3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	scancode = inb__HQ0Xhmit0RzG5MHuATBKcQ(((NU16) 96));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NIM_CHAR character;
		if (!!(((NU8)(scancode & ((NU8) 128)) == ((NU8) 0)))) goto LA4_;
		character = scanCodeToAscii__mfmfNCzuyizG3Gp9a8dDflg((NU8)(scancode ^ ((NU8) 128)));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		{
			NimStringV2 T10_;
			if (!!((((NU8)(character)) == ((NI) 0)))) goto LA8_;
			T10_.len = 0; T10_.p = NIM_NIL;
			T10_ = nimCharToStr(character);
			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T10_);
			consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(colontmpD_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA6_;
		LA8_: ;
		{
			consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ZrVepqz9a1O4OWN5tc4Iqnw_5);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA6_: ;
	}
	goto LA2_;
	LA4_: ;
	{
		NIM_CHAR character_2;
		character_2 = scanCodeToAscii__mfmfNCzuyizG3Gp9a8dDflg(scancode);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		{
			NimStringV2 T17_;
			if (!!((((NU8)(character_2)) == ((NI) 0)))) goto LA15_;
			T17_.len = 0; T17_.p = NIM_NIL;
			T17_ = nimCharToStr(character_2);
			eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T17_);
			consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(colontmpD__2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA13_;
		LA15_: ;
		{
			consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ZrVepqz9a1O4OWN5tc4Iqnw_7);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2(TM__ZrVepqz9a1O4OWN5tc4Iqnw_8);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA13_: ;
	}
	LA2_: ;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, keyboardInstall)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	installHandler(((unsigned int) 1), keyboardHandler);
	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ZrVepqz9a1O4OWN5tc4Iqnw_10);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
