/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg;
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
NU raiseId;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc__NT9bSe2DDkjdtx7j9aov2Z6g;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc__NT9bSe2DDkjdtx7j9aov2Z6g raiseAction;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* r, void* ClE_0);
void* ClE_0;
} tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ;
typedef N_CLOSURE_PTR(void, TM__ssONC9b19bD8TyoQZOwTAUxg_10) (tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* r, void* ClE_0);
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap;AllocatorObj* allocator;tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_NIMCALL(void, keyboardHandler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(NU8, inb__HQ0Xhmit0RzG5MHuATBKcQ)(NU16 port);
N_LIB_PRIVATE N_NIMCALL(void, consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ)(NimStringV2 a);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, scanCodeToAscii__KP6o4pfh11dLonOhHsuAGQ)(NU8 scancode);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x);
N_LIB_PRIVATE N_NIMCALL(void, consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2)(NimStringV2 a);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, keyboardInstall)(void);
N_NIMCALL(void, installHandler)(NI irq, tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ handler);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static const struct {
  NI cap; void* allocator; NIM_CHAR data[8+1];
} TM__ssONC9b19bD8TyoQZOwTAUxg_3 = { 8, NIM_NIL, "keyboard" };
static const NimStringV2 TM__ssONC9b19bD8TyoQZOwTAUxg_4 = {8, (NimStrPayload*)&TM__ssONC9b19bD8TyoQZOwTAUxg_3};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[24+1];
} TM__ssONC9b19bD8TyoQZOwTAUxg_5 = { 24, NIM_NIL, "Unrecognized scancode..." };
static const NimStringV2 TM__ssONC9b19bD8TyoQZOwTAUxg_6 = {24, (NimStrPayload*)&TM__ssONC9b19bD8TyoQZOwTAUxg_5};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[17+1];
} TM__ssONC9b19bD8TyoQZOwTAUxg_7 = { 17, NIM_NIL, "GOT DEBUG SIGNAL!" };
static const NimStringV2 TM__ssONC9b19bD8TyoQZOwTAUxg_8 = {17, (NimStrPayload*)&TM__ssONC9b19bD8TyoQZOwTAUxg_7};
static const NimStringV2 TM__ssONC9b19bD8TyoQZOwTAUxg_9 = {24, (NimStrPayload*)&TM__ssONC9b19bD8TyoQZOwTAUxg_5};
static const NimStringV2 TM__ssONC9b19bD8TyoQZOwTAUxg_11 = {8, (NimStrPayload*)&TM__ssONC9b19bD8TyoQZOwTAUxg_3};
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, scanCodeToAscii__KP6o4pfh11dLonOhHsuAGQ)(NU8 scancode) {	NIM_CHAR result;
{	result = (NIM_CHAR)0;
	switch (scancode) {
	case ((NI) 0):
	{
		result = 0;
		goto BeforeRet_;
	}
	break;
	case ((NI) 14):
	{
		result = 8;
		goto BeforeRet_;
	}
	break;
	case ((NI) 16):
	{
		result = 113;
		goto BeforeRet_;
	}
	break;
	case ((NI) 17):
	{
		result = 119;
		goto BeforeRet_;
	}
	break;
	case ((NI) 18):
	{
		result = 101;
		goto BeforeRet_;
	}
	break;
	case ((NI) 19):
	{
		result = 114;
		goto BeforeRet_;
	}
	break;
	case ((NI) 20):
	{
		result = 116;
		goto BeforeRet_;
	}
	break;
	case ((NI) 21):
	{
		result = 121;
		goto BeforeRet_;
	}
	break;
	case ((NI) 22):
	{
		result = 117;
		goto BeforeRet_;
	}
	break;
	case ((NI) 23):
	{
		result = 105;
		goto BeforeRet_;
	}
	break;
	case ((NI) 24):
	{
		result = 111;
		goto BeforeRet_;
	}
	break;
	case ((NI) 25):
	{
		result = 112;
		goto BeforeRet_;
	}
	break;
	case ((NI) 57):
	{
		result = 32;
		goto BeforeRet_;
	}
	break;
	default:
	{
		result = 0;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, popSafePoint)(void) {}
N_NIMCALL(void, keyboardHandler)(tyObject_registers__Mb0UOAid9c9c7v7uFPX18mcg* regs) {	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	TSafePoint TM__ssONC9b19bD8TyoQZOwTAUxg_2;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	pushSafePoint(&TM__ssONC9b19bD8TyoQZOwTAUxg_2);
	TM__ssONC9b19bD8TyoQZOwTAUxg_2.status = setjmp(TM__ssONC9b19bD8TyoQZOwTAUxg_2.context);
	if (TM__ssONC9b19bD8TyoQZOwTAUxg_2.status == 0) {
		NU8 scancode;
		scancode = inb__HQ0Xhmit0RzG5MHuATBKcQ(((NU16) 96));
		consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ssONC9b19bD8TyoQZOwTAUxg_4);
		{
			NIM_CHAR character;
			if (!!(((NU8)(scancode & ((NU8) 128)) == ((NU8) 0)))) goto LA4_;
			character = scanCodeToAscii__KP6o4pfh11dLonOhHsuAGQ((NU8)(scancode ^ ((NU8) 128)));
			{
				NimStringV2 T10_;
				if (!!((((NU8)(character)) == ((NI) 0)))) goto LA8_;
				T10_.len = 0; T10_.p = NIM_NIL;
				T10_ = nimCharToStr(character);
				eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD_), T10_);
				consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(colontmpD_);
			}
			goto LA6_;
			LA8_: ;
			{
				consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ssONC9b19bD8TyoQZOwTAUxg_6);
			}
			LA6_: ;
		}
		goto LA2_;
		LA4_: ;
		{
			NIM_CHAR character_2;
			character_2 = scanCodeToAscii__KP6o4pfh11dLonOhHsuAGQ(scancode);
			{
				NimStringV2 T17_;
				if (!!((((NU8)(character_2)) == ((NI) 0)))) goto LA15_;
				T17_.len = 0; T17_.p = NIM_NIL;
				T17_ = nimCharToStr(character_2);
				eqsink___aBBXmHFBEivKqERloP6zmA((&colontmpD__2), T17_);
				consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(colontmpD__2);
			}
			goto LA13_;
			LA15_: ;
			{
				consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ssONC9b19bD8TyoQZOwTAUxg_8);
				consoleWrite__RpCx8d9a9cozNvS9aKPon6r9cQ_2(TM__ssONC9b19bD8TyoQZOwTAUxg_9);
			}
			LA13_: ;
		}
		LA2_: ;
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
	}
	if (TM__ssONC9b19bD8TyoQZOwTAUxg_2.status != 0) reraiseException();
}
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}
N_NIMCALL(void, keyboardInstall)(void) {	void* colontmpD_;
	tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ T1_;
	colontmpD_ = (void*)0;
	colontmpD_ = 0;
	colontmpD_ = NIM_NIL;
	nimZeroMem((void*)(&T1_), sizeof(tyProc__1aExiFCFu1i6s9aK9bwfoA9bQ));
	T1_.ClP_0 = ((TM__ssONC9b19bD8TyoQZOwTAUxg_10) (keyboardHandler)); T1_.ClE_0 = colontmpD_;
	installHandler(((NI) 1), T1_);
	consoleWriteNl__RpCx8d9a9cozNvS9aKPon6r9cQ(TM__ssONC9b19bD8TyoQZOwTAUxg_11);
}
