/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
N_LIB_PRIVATE N_NIMCALL(void, outb__WHsX9cRAb9ansZ7pOaHMylNw)(NU16 port, NU8 value) {	  __asm__ __volatile__ ("outb %1, %0" : : "dN" (port), "a" (value));
  
}
N_LIB_PRIVATE N_NIMCALL(NU8, inb__HQ0Xhmit0RzG5MHuATBKcQ)(NU16 port) {	NU8 result;
	result = (NU8)0;
	asm("  inb %%dx, %%al\n"
  :"=a" (result)
  :"d" (port)
);
	return result;
}
