/* Generated by Nim Compiler v1.3.1 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NimStringV2 tyArray__c2QNJmc34bMEk131Zq7ttQ[32];
extern void isr0();
extern void isr1();
extern void isr2();
extern void isr3();
extern void isr4();
extern void isr5();
extern void isr6();
extern void isr7();
extern void isr8();
extern void isr9();
extern void isr10();
extern void isr11();
extern void isr12();
extern void isr13();
extern void isr14();
extern void isr15();
extern void isr16();
extern void isr17();
extern void isr18();
extern void isr19();
extern void isr20();
extern void isr21();
extern void isr22();
extern void isr23();
extern void isr24();
extern void isr25();
extern void isr26();
extern void isr27();
extern void isr28();
extern void isr29();
extern void isr30();
extern void isr31();

N_LIB_PRIVATE N_NIMCALL(void, isrsInstall)(void);
N_LIB_PRIVATE N_NIMCALL(void, idtSetGate__uB9aAbzjB9bRgxmfLMWFiDxw)(NU8 num, NU32 base, NU16 sel, NU8 flags);
N_LIB_PRIVATE N_NIMCALL(NU32, getIsr__DpkY9c2DnZ2BXLrXpI9cWbvg)(NI i);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_2 = { 18 | NIM_STRLIT_FLAG, "Division by zero!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_3 = {18, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_2};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_4 = { 7 | NIM_STRLIT_FLAG, "Debug!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_5 = {7, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_4};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_6 = { 24 | NIM_STRLIT_FLAG, "Non maskable interrupt!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_7 = {24, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_6};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_8 = { 7 | NIM_STRLIT_FLAG, "INT 3!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_9 = {7, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_8};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_10 = { 6 | NIM_STRLIT_FLAG, "INTO!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_11 = {6, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_10};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_12 = { 15 | NIM_STRLIT_FLAG, "Out of Bounds!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_13 = {15, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_12};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_14 = { 12 | NIM_STRLIT_FLAG, "Bad opcode!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_15 = {12, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_14};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_16 = { 26 | NIM_STRLIT_FLAG, "Co-processor unavailable!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_17 = {26, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_16};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_18 = { 14 | NIM_STRLIT_FLAG, "Double Fault!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_19 = {14, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_18};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_20 = { 30 | NIM_STRLIT_FLAG, "Co-processor segment overrun!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_21 = {30, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_20};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_22 = { 9 | NIM_STRLIT_FLAG, "Bad TSS!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_23 = {9, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_22};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_24 = { 21 | NIM_STRLIT_FLAG, "Segment not present!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_25 = {21, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_24};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_26 = { 13 | NIM_STRLIT_FLAG, "Stack fault!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_27 = {13, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_26};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_28 = { 26 | NIM_STRLIT_FLAG, "General Protection Fault!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_29 = {26, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_28};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_30 = { 12 | NIM_STRLIT_FLAG, "Page fault!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_31 = {12, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_30};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_32 = { 10 | NIM_STRLIT_FLAG, "Reserved!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_33 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const struct {
  NI cap; NIM_CHAR data[26+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_34 = { 26 | NIM_STRLIT_FLAG, "Floating point exception!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_35 = {26, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_34};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_36 = { 17 | NIM_STRLIT_FLAG, "Alignment Check!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_37 = {17, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_36};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__A9av19ak2XpYuH2KeE9b9awKsA_38 = { 15 | NIM_STRLIT_FLAG, "Machine Check!\000" };
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_39 = {15, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_38};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_40 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_41 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_42 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_43 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_44 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_45 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_46 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_47 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_48 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_49 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_50 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_51 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
static const NimStringV2 TM__A9av19ak2XpYuH2KeE9b9awKsA_52 = {10, (NimStrPayload*)&TM__A9av19ak2XpYuH2KeE9b9awKsA_32};
N_LIB_PRIVATE tyArray__c2QNJmc34bMEk131Zq7ttQ exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
N_LIB_PRIVATE N_NIMCALL(NU32, getIsr__DpkY9c2DnZ2BXLrXpI9cWbvg)(NI i) {
	NU32 result;
	result = (NU32)0;
	  switch(i) {
  case 0:
    result = isr0;
    break;
  case 1:
    result = isr1;
    break;
  case 2:
    result = isr2;
    break;
  case 3:
    result = isr3;
    break;
  case 4:
    result = isr4;
    break;
  case 5:
    result = isr5;
    break;
  case 6:
    result = isr6;
    break;
  case 7:
    result = isr7;
    break;
  case 8:
    result = isr8;
    break;
  case 9:
    result = isr9;
    break;
  case 10:
    result = isr10;
    break;
  case 11:
    result = isr11;
    break;
  case 12:
    result = isr12;
    break;
  case 13:
    result = isr13;
    break;
  case 14:
    result = isr14;
    break;
  case 15:
    result = isr15;
    break;
  case 16:
    result = isr16;
    break;
  case 17:
    result = isr17;
    break;
  case 18:
    result = isr18;
    break;
  case 19:
    result = isr19;
    break;
  case 20:
    result = isr20;
    break;
  case 21:
    result = isr21;
    break;
  case 22:
    result = isr22;
    break;
  case 23:
    result = isr23;
    break;
  case 24:
    result = isr24;
    break;
  case 25:
    result = isr25;
    break;
  case 26:
    result = isr26;
    break;
  case 27:
    result = isr27;
    break;
  case 28:
    result = isr28;
    break;
  case 29:
    result = isr29;
    break;
  case 30:
    result = isr30;
    break;
  case 31:
    result = isr31;
  }
  
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, isrsInstall)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				NU32 T4_;
				if (!(res <= ((NI) 31))) goto LA3;
				i = res;
				T4_ = (NU32)0;
				T4_ = getIsr__DpkY9c2DnZ2BXLrXpI9cWbvg(i);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				idtSetGate__uB9aAbzjB9bRgxmfLMWFiDxw(((NU8) (i)), T4_, ((NU16) 8), ((NU8) 142));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				res += ((NI) 1);
			} LA3: ;
		}
	}
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 0))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_3);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 1))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_5);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 2))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_7);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 3))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_9);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 4))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_11);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 5))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_13);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 6))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_15);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 7))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_17);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 8))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_19);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 9))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_21);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 10))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_23);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 11))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_25);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 12))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_27);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 13))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_29);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 14))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_31);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 15))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_33);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 16))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_35);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 17))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_37);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 18))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_39);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 19))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_40);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 20))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_41);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 21))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_42);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 22))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_43);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 23))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_44);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 24))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_45);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 25))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_46);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 26))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_47);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 27))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_48);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 28))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_49);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 29))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_50);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 30))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_51);
	eqsink___aBBXmHFBEivKqERloP6zmA((&exceptionMessages__aEliYTX2OYxY9aYVbXJQtcw[(((NI) 31))- 0]), TM__A9av19ak2XpYuH2KeE9b9awKsA_52);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GF7fBXzeJgtHVCogYAjhKw)(NimStringV2* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			if (!(colontmp_ < ((NI) 32))) goto LA2;
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&dest[(colontmp_)- 0]));
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
}
