/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct Exception Exception;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct TNimType TNimType;
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NF tyArray__8Z46I8ALX9cOzRsVvEcGgNA[1];
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
typedef tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ tyArray__9aTRall1siQT9bXabu2aKXUg[3500];
typedef N_NIMCALL_PTR(void*, tyProc__CnBl0b19c7EfCW9arW79aHpxg) (TNimType* typ, NI size);
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
static N_INLINE(void, initStackBottom)(void);
static N_INLINE(void, sysFatal__loKUBbrfPTCD1cUb5IkxkAsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, panic__nejvpIQXdprk37XF3Ca3wA)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, rawoutput__nejvpIQXdprk37XF3Ca3wA_2)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(AllocatorObj*, getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len);
N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
NI allocs__T3KvbObbC5lve2bgh5sQDg;
tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA;
tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg;
tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__kZNaA7u1MfSW5ZeoGvw8xg;
tyArray__8Z46I8ALX9cOzRsVvEcGgNA theHeap__XZKeHlqIPZnC9cnPDuLOhug;
NI bumpPointer__4oJE8o5HnhzaiuWX19bgtiw;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg allocator__Het9ctRSeaVb4hPekZZNCJQ;
NI globalMarkersLen__hgEFy3UCOBoalBh29asu5MA;
tyArray__9aTRall1siQT9bXabu2aKXUg globalMarkers__5ghwSgpo9cT9bT7YStQDJHVQ;
NI threadLocalMarkersLen__0RZOktgt14ljJsHMSX0iCw;
tyArray__9aTRall1siQT9bXabu2aKXUg threadLocalMarkers__pC47Nqd8F629cuTchphM5YA;
tyProc__CnBl0b19c7EfCW9arW79aHpxg newObjHook__7MxfG9bWiJTXSBSHaRhUViQ;
tyProc__ojoeKfW4VYIm36I9cpDTQIg traverseObjHook__ERY1fafvUtG4Q2MJx0nyOA;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[23+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_2 = { 23, NIM_NIL, "no exception to reraise" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_3 = {23, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_2};
static N_INLINE(void, initStackBottom)(void) {}
N_LIB_PRIVATE N_NIMCALL(void, rawoutput__nejvpIQXdprk37XF3Ca3wA_2)(NimStringV2 s) {	NU16* vram;
	vram = ((NU16*) 753664);
}
N_LIB_PRIVATE N_NIMCALL(void, panic__nejvpIQXdprk37XF3Ca3wA)(NimStringV2 s) {	rawoutput__nejvpIQXdprk37XF3Ca3wA_2(s);
}
static N_INLINE(void, sysFatal__loKUBbrfPTCD1cUb5IkxkAsystem)(NimStringV2 message) {	panic__nejvpIQXdprk37XF3Ca3wA(message);
}
N_NIMCALL(void, reraiseException)(void) {	sysFatal__loKUBbrfPTCD1cUb5IkxkAsystem(TM__Q5wkpxktOdTGvlSRo9bzt9aw_3);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest) {	if ((*dest).p && (*dest).p->allocator) {
 (*dest).p->allocator->dealloc((*dest).p->allocator, (*dest).p, (*dest).p->cap + 1 + sizeof(NI) + sizeof(void*)); }
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src) {	if ((*dest).len && (*dest).p != src.p) {	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest);
	}
(*dest).len = src.len; (*dest).p = src.p;
}
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}
N_NIMCALL(NimStringV2, mnewString)(NI len) {	NimStringV2 result;
	NimStrPayload* colontmpD_;
	NI colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	colontmpD_ = (NimStrPayload*)0;
	colontmpD__2 = (NI)0;
	{
		if (!(len <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		colontmpD_ = 0;
		colontmpD_ = NIM_NIL;
		result.p = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		AllocatorObj* allocator;
		NimStrPayload* p;
		void* T6_;
		NimStrPayload* blitTmp;
		allocator = getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw();
		T6_ = (void*)0;
		T6_ = (*allocator).alloc(allocator, (NI)((NI)((NI)(len + ((NI) 1)) + ((NI) 4)) + ((NI) 4)), ((NI) 8));
		p = ((NimStrPayload*) (T6_));
		(*p).allocator = allocator;
		(*p).cap = len;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD__2 = 0;
		colontmpD__2 = len;
		result.len = colontmpD__2;
		blitTmp = p;
		p = 0;
		result.p = blitTmp;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {	nimCopyMem(dest, source, size);
}
N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s) {	{
		NIM_BOOL T3_;
		NimStrPayload* oldP;
		AllocatorObj* allocator;
		void* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == NIM_NIL));
		if (!(T3_)) goto LA4_;
		T3_ = ((*(*s).p).allocator == NIM_NIL);
		LA4_: ;
		if (!T3_) goto LA5_;
		oldP = (*s).p;
		allocator = getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw();
		T7_ = (void*)0;
		T7_ = (*allocator).alloc(allocator, (NI)((NI)((NI)((*s).len + ((NI) 1)) + ((NI) 4)) + ((NI) 4)), ((NI) 8));
		(*s).p = ((NimStrPayload*) (T7_));
		(*(*s).p).allocator = allocator;
		(*(*s).p).cap = (*s).len;
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*s).p).data[((NI) 0)]))), ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((NI)((*s).len + ((NI) 1)))));
	}
	LA5_: ;
}
N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x) {	NimStringV2 result;
	NimStringV2 T1_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = mnewString(((NI) 1));
	eqsink___aBBXmHFBEivKqERloP6zmA((&result), T1_);
	nimPrepareStrMutationV2((&result));
	result.p->data[((NI) 0)] = x;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
{
	initStackBottom();
	bumpPointer__4oJE8o5HnhzaiuWX19bgtiw = ((NI) (ptrdiff_t) (theHeap__XZKeHlqIPZnC9cnPDuLOhug));
}
}

