/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
struct RootObj {
TNimType* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
NU raiseId;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc__NT9bSe2DDkjdtx7j9aov2Z6g;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc__NT9bSe2DDkjdtx7j9aov2Z6g raiseAction;
};
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};


#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap;AllocatorObj* allocator;NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap;AllocatorObj* allocator;tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__dJtt8Xj30kt9bCQK1n8AO9cw)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__45fPtFhY4FavRaYwDhRfuA)(NimStringV2* s, NimStringV2 x);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_NIMCALL(void, reraiseException)(void);
static const struct {
  NI cap; void* allocator; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_3 = { 2, NIM_NIL, "@[" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_3};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = { 2, NIM_NIL, ", " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_5};
static const struct {
  NI cap; void* allocator; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_7 = { 1, NIM_NIL, "]" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_8 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_7};
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {	{
		if (!(((NI) 0) < src.len)) goto LA3_;
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(src.len + ((NI) 1)))));
		(*dest).len += src.len;
	}
	LA3_: ;
}
static N_INLINE(void, popSafePoint)(void) {}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__dJtt8Xj30kt9bCQK1n8AO9cw)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix) {	NimStringV2 result;
	NimStringV2 value;
	TSafePoint TM__n49a9aYp5BrbXv9a6OCpJYm0g_2;
	result.len = 0; result.p = NIM_NIL;
	value.len = 0; value.p = NIM_NIL;
	pushSafePoint(&TM__n49a9aYp5BrbXv9a6OCpJYm0g_2);
	TM__n49a9aYp5BrbXv9a6OCpJYm0g_2.status = setjmp(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2.context);
	if (TM__n49a9aYp5BrbXv9a6OCpJYm0g_2.status == 0) {
		NIM_BOOL firstElement;
		eq___aBBXmHFBEivKqERloP6zmA_2((&result), prefix);
		firstElement = NIM_TRUE;
		{
			NI i;
			NI L;
			NI T3_;
			i = ((NI) 0);
			T3_ = x.len;
			L = T3_;
			{
				while (1) {
					if (!(i < L)) goto LA5;
					eq___aBBXmHFBEivKqERloP6zmA_2((&value), x.p->data[i]);
					{
						if (!firstElement) goto LA8_;
						firstElement = NIM_FALSE;
					}
					goto LA6_;
					LA8_: ;
					{
						prepareAdd((&result), separator.len + 0);
appendString((&result), separator);
					}
					LA6_: ;
					addQuoted__45fPtFhY4FavRaYwDhRfuA((&result), value);
					i += ((NI) 1);
				} LA5: ;
			}
		}
		prepareAdd((&result), suffix.len + 0);
appendString((&result), suffix);
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&value));
	}
	if (TM__n49a9aYp5BrbXv9a6OCpJYm0g_2.status != 0) reraiseException();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___xqL1qTIQGkhdyM4F59c1P9aw)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ x) {	NimStringV2 result;
	NimStringV2 T1_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = collectionToString__dJtt8Xj30kt9bCQK1n8AO9cw(x, TM__n49a9aYp5BrbXv9a6OCpJYm0g_4, TM__n49a9aYp5BrbXv9a6OCpJYm0g_6, TM__n49a9aYp5BrbXv9a6OCpJYm0g_8);
	eqsink___aBBXmHFBEivKqERloP6zmA((&result), T1_);
	return result;
}
