/* Generated by Nim Compiler v1.1.0 */
/*   (c) 2019 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct Exception Exception;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct TNimType TNimType;
typedef struct NimStrPayload NimStrPayload;
typedef struct AllocatorObj AllocatorObj;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ tySequence__P3ZXR4R07tiqmqKWxuHhKQ;
typedef struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content;
typedef struct tyObject_NimSeqV2__K1S1n9bl462sjw60a5o2XuQ tyObject_NimSeqV2__K1S1n9bl462sjw60a5o2XuQ;
typedef struct tyObject_NimSeqPayload__HeALk1XwB1qN9bLqfKBC5jQ tyObject_NimSeqPayload__HeALk1XwB1qN9bLqfKBC5jQ;
typedef struct tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g;
typedef struct tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug;
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NF tyArray__8Z46I8ALX9cOzRsVvEcGgNA[1];
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
typedef tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ tyArray__9aTRall1siQT9bXabu2aKXUg[3500];
typedef N_NIMCALL_PTR(void*, tyProc__CnBl0b19c7EfCW9arW79aHpxg) (TNimType* typ, NI size);
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
struct NimStrPayload {
NI cap;
AllocatorObj* allocator;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimType {
void* destructor;
NI size;
NCSTRING name;
};
typedef N_NIMCALL_PTR(void*, tyProc__g4DU8Xso7TeLfKjjMA54hg) (AllocatorObj* a, NI size, NI alignment);
typedef N_NIMCALL_PTR(void, tyProc__f0fmYWZ9bBl5n2coKW0dYBQ) (AllocatorObj* a, void* p, NI size);
typedef N_NIMCALL_PTR(void*, tyProc__pc9bof8Viqlm9byLAeLaBy4g) (AllocatorObj* a, void* p, NI oldSize, NI newSize);
typedef N_NIMCALL_PTR(void, tyProc__up7108S0Kt9cUg781lCWRSQ) (AllocatorObj* a);
typedef NU8 tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg;
struct AllocatorObj {
TNimType* m_type;
tyProc__g4DU8Xso7TeLfKjjMA54hg alloc;
tyProc__f0fmYWZ9bBl5n2coKW0dYBQ dealloc;
tyProc__pc9bof8Viqlm9byLAeLaBy4g realloc;
tyProc__up7108S0Kt9cUg781lCWRSQ deallocAll;
tySet_tyEnum_AllocatorFlag__djJDT3jOEYT7cpwNwzEzRg flags;
NCSTRING name;
NI allocCount;
NI deallocCount;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ {
  NI len; tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content* p;
};
struct tyObject_NimSeqV2__K1S1n9bl462sjw60a5o2XuQ {
NI len;
tyObject_NimSeqPayload__HeALk1XwB1qN9bLqfKBC5jQ* p;
};
struct tyObject_NimSeqPayload__HeALk1XwB1qN9bLqfKBC5jQ {
NI cap;
AllocatorObj* allocator;
tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* data[SEQ_DECL_SIZE];
};
struct tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug {
NI cap;
AllocatorObj* allocator;
};


#ifndef tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
#define tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content_PP
struct tySequence__P3ZXR4R07tiqmqKWxuHhKQ_Content { NI cap;AllocatorObj* allocator;tyObject_FilecolonObjectType___58YX0cMuG0m6t7NYxd6S2g* data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, initStackBottom)(void);
static N_INLINE(void, sysFatal__loKUBbrfPTCD1cUb5IkxkAsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, panic__nejvpIQXdprk37XF3Ca3wA)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, rawoutput__nejvpIQXdprk37XF3Ca3wA_2)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(AllocatorObj*, getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw)(void);
N_NIMCALL(NimStringV2, mnewString)(NI len);
N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s);
static N_INLINE(size_t, nimCStrLen)(NCSTRING a);
N_NIMCALL(void, nimAsgnStrV2)(NimStringV2* a, NimStringV2 b);
N_LIB_PRIVATE N_NIMCALL(void, shrink__jcRF3FoLaxnIo2I0g9a9bNvg)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* x, NI newLen);
N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize);
N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize);
static N_INLINE(NI, resize__cOCDWr16YD4j3dBrbbH3yQsystem)(NI old);
NI allocs__T3KvbObbC5lve2bgh5sQDg;
tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA;
tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg;
tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__kZNaA7u1MfSW5ZeoGvw8xg;
tyArray__8Z46I8ALX9cOzRsVvEcGgNA theHeap__XZKeHlqIPZnC9cnPDuLOhug;
NI bumpPointer__4oJE8o5HnhzaiuWX19bgtiw;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg allocator__Het9ctRSeaVb4hPekZZNCJQ;
NI globalMarkersLen__hgEFy3UCOBoalBh29asu5MA;
tyArray__9aTRall1siQT9bXabu2aKXUg globalMarkers__5ghwSgpo9cT9bT7YStQDJHVQ;
NI threadLocalMarkersLen__0RZOktgt14ljJsHMSX0iCw;
tyArray__9aTRall1siQT9bXabu2aKXUg threadLocalMarkers__pC47Nqd8F629cuTchphM5YA;
tyProc__CnBl0b19c7EfCW9arW79aHpxg newObjHook__7MxfG9bWiJTXSBSHaRhUViQ;
tyProc__ojoeKfW4VYIm36I9cpDTQIg traverseObjHook__ERY1fafvUtG4Q2MJx0nyOA;
static const struct {
  NI cap; void* allocator; NIM_CHAR data[23+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_2 = { 23, NIM_NIL, "no exception to reraise" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_3 = {23, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_2};
static N_INLINE(void, initStackBottom)(void) {}
N_LIB_PRIVATE N_NIMCALL(void, rawoutput__nejvpIQXdprk37XF3Ca3wA_2)(NimStringV2 s) {	NU16* vram;
	vram = ((NU16*) 753664);
}
N_LIB_PRIVATE N_NIMCALL(void, panic__nejvpIQXdprk37XF3Ca3wA)(NimStringV2 s) {	rawoutput__nejvpIQXdprk37XF3Ca3wA_2(s);
}
static N_INLINE(void, sysFatal__loKUBbrfPTCD1cUb5IkxkAsystem)(NimStringV2 message) {	panic__nejvpIQXdprk37XF3Ca3wA(message);
}
N_NIMCALL(void, reraiseException)(void) {	sysFatal__loKUBbrfPTCD1cUb5IkxkAsystem(TM__Q5wkpxktOdTGvlSRo9bzt9aw_3);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest) {	if ((*dest).p && (*dest).p->allocator) {
 (*dest).p->allocator->dealloc((*dest).p->allocator, (*dest).p, (*dest).p->cap + 1 + sizeof(NI) + sizeof(void*)); }
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src) {	if ((*dest).len && (*dest).p != src.p) {	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest);
	}
(*dest).len = src.len; (*dest).p = src.p;
}
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
}
N_NIMCALL(NimStringV2, mnewString)(NI len) {	NimStringV2 result;
	NimStrPayload* colontmpD_;
	NI colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	colontmpD_ = (NimStrPayload*)0;
	colontmpD__2 = (NI)0;
	{
		if (!(len <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		colontmpD_ = 0;
		colontmpD_ = NIM_NIL;
		result.p = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		AllocatorObj* allocator;
		NimStrPayload* p;
		void* T6_;
		NimStrPayload* blitTmp;
		allocator = getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw();
		T6_ = (void*)0;
		T6_ = (*allocator).alloc(allocator, (NI)((NI)((NI)(len + ((NI) 1)) + ((NI) 4)) + ((NI) 4)), ((NI) 8));
		p = ((NimStrPayload*) (T6_));
		(*p).allocator = allocator;
		(*p).cap = len;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD__2 = 0;
		colontmpD__2 = len;
		result.len = colontmpD__2;
		blitTmp = p;
		p = 0;
		result.p = blitTmp;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {	nimCopyMem(dest, source, size);
}
N_NIMCALL(void, nimPrepareStrMutationV2)(NimStringV2* s) {	{
		NIM_BOOL T3_;
		NimStrPayload* oldP;
		AllocatorObj* allocator;
		void* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == NIM_NIL));
		if (!(T3_)) goto LA4_;
		T3_ = ((*(*s).p).allocator == NIM_NIL);
		LA4_: ;
		if (!T3_) goto LA5_;
		oldP = (*s).p;
		allocator = getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw();
		T7_ = (void*)0;
		T7_ = (*allocator).alloc(allocator, (NI)((NI)((NI)((*s).len + ((NI) 1)) + ((NI) 4)) + ((NI) 4)), ((NI) 8));
		(*s).p = ((NimStrPayload*) (T7_));
		(*(*s).p).allocator = allocator;
		(*(*s).p).cap = (*s).len;
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*s).p).data[((NI) 0)]))), ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((NI)((*s).len + ((NI) 1)))));
	}
	LA5_: ;
}
N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x) {	NimStringV2 result;
	NimStringV2 T1_;
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = mnewString(((NI) 1));
	eqsink___aBBXmHFBEivKqERloP6zmA((&result), T1_);
	nimPrepareStrMutationV2((&result));
	result.p->data[((NI) 0)] = x;
	return result;
}
static N_INLINE(size_t, nimCStrLen)(NCSTRING a) {	size_t result;
	result = (size_t)0;
	result = strlen(a);
	return result;
}
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s) {	int T1_;
	T1_ = (int)0;
	T1_ = fwrite(((void*) (s)), ((size_t) 1), ((size_t) ((s ? nimCStrLen(s) : 0))), f);
	(void)(T1_);
}
N_NIMCALL(void, nimRawDispose)(void* p) {	NIM_BOOL hasDanglingRefs;
	hasDanglingRefs = !(((*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) ((NI)((NU32)(((NI) (ptrdiff_t) (p))) - (NU32)(((NI) 4)))))).rc == ((NI) 0)));
	{
		if (!hasDanglingRefs) goto LA3_;
		rawWrite(stderr, "[FATAL] dangling references exist\012");
		exit(((NI) 1));
	}
	LA3_: ;
	free(((void*) ((NI)((NU32)(((NI) (ptrdiff_t) (p))) - (NU32)(((NI) 4))))));
	{
		if (!(((NI) 0) < allocs__T3KvbObbC5lve2bgh5sQDg)) goto LA7_;
		allocs__T3KvbObbC5lve2bgh5sQDg -= ((NI) 1);
	}
	goto LA5_;
	LA7_: ;
	{
		rawWrite(stderr, "[FATAL] unpaired dealloc\012");
		exit(((NI) 1));
	}
	LA5_: ;
}
N_NIMCALL(void*, nimNewObj)(NI size) {	void* result;
	NI s;
	void* orig;
	result = (void*)0;
	s = (NI)(size + ((NI) 4));
	orig = malloc(((size_t) (s)));
	nimZeroMem(orig, ((NI) (s)));
	result = ((void*) ((NI)((NU32)(((NI) (ptrdiff_t) (orig))) + (NU32)(((NI) 4)))));
	allocs__T3KvbObbC5lve2bgh5sQDg += ((NI) 1);
	return result;
}
N_NIMCALL(void, nimAsgnStrV2)(NimStringV2* a, NimStringV2 b) {{	{
		if (!((*a).p == b.p)) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (b.p == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = ((*b.p).allocator == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		{
			NIM_BOOL T13_;
			T13_ = (NIM_BOOL)0;
			T13_ = ((*a).p == NIM_NIL);
			if (T13_) goto LA14_;
			T13_ = ((*(*a).p).allocator == NIM_NIL);
			LA14_: ;
			if (!!(T13_)) goto LA15_;
			(*(*(*a).p).allocator).dealloc((*(*a).p).allocator, ((void*) ((*a).p)), (NI)((NI)((NI)((*(*a).p).cap + ((NI) 1)) + ((NI) 4)) + ((NI) 4)));
		}
		LA15_: ;
		(*a).len = b.len;
		(*a).p = b.p;
	}
	goto LA5_;
	LA9_: ;
	{
		{
			NIM_BOOL T20_;
			NIM_BOOL T21_;
			AllocatorObj* allocator;
			void* T39_;
			T20_ = (NIM_BOOL)0;
			T21_ = (NIM_BOOL)0;
			T21_ = ((*a).p == NIM_NIL);
			if (T21_) goto LA22_;
			T21_ = ((*(*a).p).allocator == NIM_NIL);
			LA22_: ;
			T20_ = T21_;
			if (T20_) goto LA23_;
			T20_ = ((*(*a).p).cap < b.len);
			LA23_: ;
			if (!T20_) goto LA24_;
			{
				NIM_BOOL T28_;
				T28_ = (NIM_BOOL)0;
				T28_ = !(((*a).p == NIM_NIL));
				if (!(T28_)) goto LA29_;
				T28_ = !(((*(*a).p).allocator == NIM_NIL));
				LA29_: ;
				if (!T28_) goto LA30_;
				allocator = (*(*a).p).allocator;
			}
			goto LA26_;
			LA30_: ;
			{
				allocator = getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw();
			}
			LA26_: ;
			{
				NIM_BOOL T35_;
				T35_ = (NIM_BOOL)0;
				T35_ = ((*a).p == NIM_NIL);
				if (T35_) goto LA36_;
				T35_ = ((*(*a).p).allocator == NIM_NIL);
				LA36_: ;
				if (!!(T35_)) goto LA37_;
				(*(*(*a).p).allocator).dealloc((*(*a).p).allocator, ((void*) ((*a).p)), (NI)((NI)((NI)((*(*a).p).cap + ((NI) 1)) + ((NI) 4)) + ((NI) 4)));
			}
			LA37_: ;
			T39_ = (void*)0;
			T39_ = (*allocator).alloc(allocator, (NI)((NI)((NI)(b.len + ((NI) 1)) + ((NI) 4)) + ((NI) 4)), ((NI) 8));
			(*a).p = ((NimStrPayload*) (T39_));
			(*(*a).p).allocator = allocator;
			(*(*a).p).cap = b.len;
		}
		LA24_: ;
		(*a).len = b.len;
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*a).p).data[((NI) 0)]))), ((void*) ((&(*b.p).data[((NI) 0)]))), ((NI) ((NI)(b.len + ((NI) 1)))));
	}
	LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src) {	nimAsgnStrV2(dest, src);
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__jcRF3FoLaxnIo2I0g9a9bNvg)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* x, NI newLen) {	{
		NI i;
		NI colontmp_;
		NI colontmp__2;
		NI T2_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp__2 = (NI)0;
		T2_ = (*x).len;
		colontmp_ = (NI)(T2_ - ((NI) 1));
		colontmp__2 = ((NI) (newLen));
		res = colontmp_;
		{
			while (1) {
				if (!(colontmp__2 <= res)) goto LA4;
				i = res;
				res -= ((NI) 1);
			} LA4: ;
		}
	}
	(*((tyObject_NimSeqV2__K1S1n9bl462sjw60a5o2XuQ*) (x))).len = ((NI) (newLen));
}
N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize) {	void* result;
	result = (void*)0;
	{
		AllocatorObj* allocator;
		tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug* p;
		void* T5_;
		if (!(((NI) 0) < cap)) goto LA3_;
		allocator = getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw();
		T5_ = (void*)0;
		T5_ = (*allocator).alloc(allocator, (NI)((NI)((NI)(cap * elemSize) + ((NI) 4)) + ((NI) 4)), ((NI) 8));
		p = ((tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug*) (T5_));
		(*p).allocator = allocator;
		(*p).cap = cap;
		result = ((void*) (p));
	}
	goto LA1_;
	LA3_: ;
	{
		result = NIM_NIL;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, resize__cOCDWr16YD4j3dBrbbH3yQsystem)(NI old) {	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}
N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize) {	void* result;
	result = (void*)0;
	{
		if (!(addlen <= ((NI) 0))) goto LA3_;
		result = p;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(p == NIM_NIL)) goto LA6_;
		result = newSeqPayload((NI)(len + addlen), elemSize);
	}
	goto LA1_;
	LA6_: ;
	{
		tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug* p_2;
		NI cap;
		NI T9_;
		p_2 = ((tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug*) (p));
		T9_ = (NI)0;
		T9_ = resize__cOCDWr16YD4j3dBrbbH3yQsystem((*p_2).cap);
		cap = ((T9_ >= (NI)(len + addlen)) ? T9_ : (NI)(len + addlen));
		{
			AllocatorObj* allocator;
			tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug* q;
			void* T14_;
			if (!((*p_2).allocator == NIM_NIL)) goto LA12_;
			allocator = getLocalAllocator__9c1gnSB0ooi2TBl9a6M3edDw();
			T14_ = (void*)0;
			T14_ = (*allocator).alloc(allocator, (NI)(((NI) 8) + (NI)(elemSize * cap)), ((NI) 8));
			q = ((tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug*) (T14_));
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((NI)((NU32)(((NI) (ptrdiff_t) (q))) + (NU32)(((NI) 8))))), ((void*) ((NI)((NU32)(((NI) (ptrdiff_t) (p_2))) + (NU32)(((NI) 8))))), ((NI) ((NI)(len * elemSize))));
			(*q).allocator = allocator;
			(*q).cap = cap;
			result = ((void*) (q));
		}
		goto LA10_;
		LA12_: ;
		{
			AllocatorObj* allocator_2;
			tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug* q_2;
			void* T16_;
			allocator_2 = (*p_2).allocator;
			T16_ = (void*)0;
			T16_ = (*allocator_2).realloc(allocator_2, ((void*) (p_2)), (NI)(((NI) 8) + (NI)(elemSize * (*p_2).cap)), (NI)(((NI) 8) + (NI)(elemSize * cap)));
			q_2 = ((tyObject_PayloadBase__9aSxo9b89c9bCiw9c6daID6JXug*) (T16_));
			(*q_2).allocator = allocator_2;
			(*q_2).cap = cap;
			result = ((void*) (q_2));
		}
		LA10_: ;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setLen__9cFY9csU2Vy6aqPrO9bDoi0NA)(tySequence__P3ZXR4R07tiqmqKWxuHhKQ* s, NI newlen) {{	{
		NI T3_;
		T3_ = (*s).len;
		if (!(((NI) (newlen)) < T3_)) goto LA4_;
		shrink__jcRF3FoLaxnIo2I0g9a9bNvg(s, newlen);
	}
	goto LA1_;
	LA4_: ;
	{
		NI oldLen;
		NI T7_;
		tyObject_NimSeqV2__K1S1n9bl462sjw60a5o2XuQ* xu;
		T7_ = (*s).len;
		oldLen = T7_;
		{
			if (!(((NI) (newlen)) <= oldLen)) goto LA10_;
			goto BeforeRet_;
		}
		LA10_: ;
		xu = ((tyObject_NimSeqV2__K1S1n9bl462sjw60a5o2XuQ*) (s));
		{
			NIM_BOOL T14_;
			void* T18_;
			T14_ = (NIM_BOOL)0;
			T14_ = ((*xu).p == NIM_NIL);
			if (T14_) goto LA15_;
			T14_ = ((*(*xu).p).cap < ((NI) (newlen)));
			LA15_: ;
			if (!T14_) goto LA16_;
			T18_ = (void*)0;
			T18_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), (NI)(((NI) (newlen)) - oldLen), ((NI) 4));
			(*xu).p = ((tyObject_NimSeqPayload__HeALk1XwB1qN9bLqfKBC5jQ*) (T18_));
		}
		LA16_: ;
		(*xu).len = ((NI) (newlen));
	}
	LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
{
	initStackBottom();
	bumpPointer__4oJE8o5HnhzaiuWX19bgtiw = ((NI) (ptrdiff_t) (theHeap__XZKeHlqIPZnC9cnPDuLOhug));
}
}

